//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.28 at 06:22:34 PM GMT+07:00 
//


package dn.servicemix.test.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.dn.com}ModelA"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.dn.com}ShowActorRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelA",
    "message",
    "showActorRequest"
})
@XmlRootElement(name = "ShowActorResponse")
public class ShowActorResponse {

    @XmlElement(name = "ModelA", required = true)
    protected ModelA modelA;
    @XmlElement(required = true)
    protected String message;
    @XmlElement(name = "ShowActorRequest", required = true)
    protected ShowActorRequest showActorRequest;

    /**
     * Gets the value of the modelA property.
     * 
     * @return
     *     possible object is
     *     {@link ModelA }
     *     
     */
    public ModelA getModelA() {
        return modelA;
    }

    /**
     * Sets the value of the modelA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelA }
     *     
     */
    public void setModelA(ModelA value) {
        this.modelA = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the showActorRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ShowActorRequest }
     *     
     */
    public ShowActorRequest getShowActorRequest() {
        return showActorRequest;
    }

    /**
     * Sets the value of the showActorRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShowActorRequest }
     *     
     */
    public void setShowActorRequest(ShowActorRequest value) {
        this.showActorRequest = value;
    }

}
