<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns="http://www.dn.com"
                  xmlns:dn="http://www.dn.com"
                  targetNamespace="http://www.dn.com">

    <wsdl:types>
        <xsd:schema targetNamespace="http://www.dn.com" elementFormDefault="qualified">
            <xsd:import namespace="http://www.dn.com"
                        schemaLocation="srva.xsd"/>
        </xsd:schema>
    </wsdl:types>

	<!-- Messages -->
    <wsdl:message name="ShowActorRequest">
        <wsdl:part name="payload" element="dn:ShowActorRequest"/>
    </wsdl:message>
    <wsdl:message name="ShowActorResponse">
        <wsdl:part name="payload" element="dn:ShowActorResponse"/>
    </wsdl:message>

	<!-- Port type -->
    <wsdl:portType name="ServiceAEndpoint">
    
        <wsdl:operation name="ShowActor">
            <wsdl:input message="ShowActorRequest"/>
            <wsdl:output message="ShowActorResponse"/>
        </wsdl:operation>
        
    </wsdl:portType>

	<!-- Binding -->
    <wsdl:binding name="ServiceASOAPBinding" type="ServiceAEndpoint">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        
        <wsdl:operation name="ShowActor">
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

	<!-- Service -->
    <wsdl:service name="ServiceA">
        <wsdl:port binding="ServiceASOAPBinding" name="ServiceAEndpoint">
            <soap:address location="http://localhost:8181/srva"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>