package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments  implements java.io.Serializable {


     private int departmentId;
     private Directorates directorates;
     private String name;
     private Serializable shortDesc;
     private int contactId;
     private Boolean copyAddr;
     private String addr1;
     private String addr2;
     private String addr3;
     private String postCode;
     private String town;
     private String county;
     private String country;
     private int typeOfBusinessId;
     private Serializable fullDesc;
     private String phoneNumber;
     private String fax;
     private String email;
     private String webAddr;
     private boolean isActive;
     private Set teamses = new HashSet(0);

    public Departments() {
    }

	
    public Departments(int departmentId, Directorates directorates, String name, Serializable shortDesc, int contactId, String postCode, int typeOfBusinessId, boolean isActive) {
        this.departmentId = departmentId;
        this.directorates = directorates;
        this.name = name;
        this.shortDesc = shortDesc;
        this.contactId = contactId;
        this.postCode = postCode;
        this.typeOfBusinessId = typeOfBusinessId;
        this.isActive = isActive;
    }
    public Departments(int departmentId, Directorates directorates, String name, Serializable shortDesc, int contactId, Boolean copyAddr, String addr1, String addr2, String addr3, String postCode, String town, String county, String country, int typeOfBusinessId, Serializable fullDesc, String phoneNumber, String fax, String email, String webAddr, boolean isActive, Set teamses) {
       this.departmentId = departmentId;
       this.directorates = directorates;
       this.name = name;
       this.shortDesc = shortDesc;
       this.contactId = contactId;
       this.copyAddr = copyAddr;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.addr3 = addr3;
       this.postCode = postCode;
       this.town = town;
       this.county = county;
       this.country = country;
       this.typeOfBusinessId = typeOfBusinessId;
       this.fullDesc = fullDesc;
       this.phoneNumber = phoneNumber;
       this.fax = fax;
       this.email = email;
       this.webAddr = webAddr;
       this.isActive = isActive;
       this.teamses = teamses;
    }
   
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }
    public Directorates getDirectorates() {
        return this.directorates;
    }
    
    public void setDirectorates(Directorates directorates) {
        this.directorates = directorates;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Serializable getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(Serializable shortDesc) {
        this.shortDesc = shortDesc;
    }
    public int getContactId() {
        return this.contactId;
    }
    
    public void setContactId(int contactId) {
        this.contactId = contactId;
    }
    public Boolean getCopyAddr() {
        return this.copyAddr;
    }
    
    public void setCopyAddr(Boolean copyAddr) {
        this.copyAddr = copyAddr;
    }
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }
    public String getAddr3() {
        return this.addr3;
    }
    
    public void setAddr3(String addr3) {
        this.addr3 = addr3;
    }
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public int getTypeOfBusinessId() {
        return this.typeOfBusinessId;
    }
    
    public void setTypeOfBusinessId(int typeOfBusinessId) {
        this.typeOfBusinessId = typeOfBusinessId;
    }
    public Serializable getFullDesc() {
        return this.fullDesc;
    }
    
    public void setFullDesc(Serializable fullDesc) {
        this.fullDesc = fullDesc;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebAddr() {
        return this.webAddr;
    }
    
    public void setWebAddr(String webAddr) {
        this.webAddr = webAddr;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getTeamses() {
        return this.teamses;
    }
    
    public void setTeamses(Set teamses) {
        this.teamses = teamses;
    }




}


