package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Facilities generated by hbm2java
 */
public class Facilities  implements java.io.Serializable {


     private int facilityId;
     private Contacts contacts;
     private int facilityType;
     private Serializable facilityDescription;
     private Integer roomCapacity;
     private Integer roomSize;
     private Boolean roomConnectivity;
     private Boolean equipmentAvailable;
     private String roomEquipmentNotes;
     private Integer connectivityType;
     private String wirelessAccessInfomation;
     private String roomHost;
     private boolean isActive;
     private int premiseId;
     private String facilityTypeName;
     private String leedContact;
     private String contactName;

    public Facilities() {
    }

	
    public Facilities(int facilityId, int facilityType, Serializable facilityDescription, boolean isActive, int premiseId) {
        this.facilityId = facilityId;
        this.facilityType = facilityType;
        this.facilityDescription = facilityDescription;
        this.isActive = isActive;
        this.premiseId = premiseId;
    }
    public Facilities(int facilityId, Contacts contacts, int facilityType, Serializable facilityDescription, Integer roomCapacity, Integer roomSize, Boolean roomConnectivity, Boolean equipmentAvailable, String roomEquipmentNotes, Integer connectivityType, String wirelessAccessInfomation, String roomHost, boolean isActive, int premiseId, String facilityTypeName, String leedContact, String contactName) {
       this.facilityId = facilityId;
       this.contacts = contacts;
       this.facilityType = facilityType;
       this.facilityDescription = facilityDescription;
       this.roomCapacity = roomCapacity;
       this.roomSize = roomSize;
       this.roomConnectivity = roomConnectivity;
       this.equipmentAvailable = equipmentAvailable;
       this.roomEquipmentNotes = roomEquipmentNotes;
       this.connectivityType = connectivityType;
       this.wirelessAccessInfomation = wirelessAccessInfomation;
       this.roomHost = roomHost;
       this.isActive = isActive;
       this.premiseId = premiseId;
       this.facilityTypeName = facilityTypeName;
       this.leedContact = leedContact;
       this.contactName = contactName;
    }
   
    public int getFacilityId() {
        return this.facilityId;
    }
    
    public void setFacilityId(int facilityId) {
        this.facilityId = facilityId;
    }
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }
    public int getFacilityType() {
        return this.facilityType;
    }
    
    public void setFacilityType(int facilityType) {
        this.facilityType = facilityType;
    }
    public Serializable getFacilityDescription() {
        return this.facilityDescription;
    }
    
    public void setFacilityDescription(Serializable facilityDescription) {
        this.facilityDescription = facilityDescription;
    }
    public Integer getRoomCapacity() {
        return this.roomCapacity;
    }
    
    public void setRoomCapacity(Integer roomCapacity) {
        this.roomCapacity = roomCapacity;
    }
    public Integer getRoomSize() {
        return this.roomSize;
    }
    
    public void setRoomSize(Integer roomSize) {
        this.roomSize = roomSize;
    }
    public Boolean getRoomConnectivity() {
        return this.roomConnectivity;
    }
    
    public void setRoomConnectivity(Boolean roomConnectivity) {
        this.roomConnectivity = roomConnectivity;
    }
    public Boolean getEquipmentAvailable() {
        return this.equipmentAvailable;
    }
    
    public void setEquipmentAvailable(Boolean equipmentAvailable) {
        this.equipmentAvailable = equipmentAvailable;
    }
    public String getRoomEquipmentNotes() {
        return this.roomEquipmentNotes;
    }
    
    public void setRoomEquipmentNotes(String roomEquipmentNotes) {
        this.roomEquipmentNotes = roomEquipmentNotes;
    }
    public Integer getConnectivityType() {
        return this.connectivityType;
    }
    
    public void setConnectivityType(Integer connectivityType) {
        this.connectivityType = connectivityType;
    }
    public String getWirelessAccessInfomation() {
        return this.wirelessAccessInfomation;
    }
    
    public void setWirelessAccessInfomation(String wirelessAccessInfomation) {
        this.wirelessAccessInfomation = wirelessAccessInfomation;
    }
    public String getRoomHost() {
        return this.roomHost;
    }
    
    public void setRoomHost(String roomHost) {
        this.roomHost = roomHost;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public int getPremiseId() {
        return this.premiseId;
    }
    
    public void setPremiseId(int premiseId) {
        this.premiseId = premiseId;
    }
    public String getFacilityTypeName() {
        return this.facilityTypeName;
    }
    
    public void setFacilityTypeName(String facilityTypeName) {
        this.facilityTypeName = facilityTypeName;
    }
    public String getLeedContact() {
        return this.leedContact;
    }
    
    public void setLeedContact(String leedContact) {
        this.leedContact = leedContact;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }




}


