package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA



/**
 * OrganisationProgramme generated by hbm2java
 */
public class OrganisationProgramme  implements java.io.Serializable {


     private int id;
     private Organisations organisations;
     private Programmes programmes;

    public OrganisationProgramme() {
    }

    public OrganisationProgramme(int id, Organisations organisations, Programmes programmes) {
       this.id = id;
       this.organisations = organisations;
       this.programmes = programmes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Organisations getOrganisations() {
        return this.organisations;
    }
    
    public void setOrganisations(Organisations organisations) {
        this.organisations = organisations;
    }
    public Programmes getProgrammes() {
        return this.programmes;
    }
    
    public void setProgrammes(Programmes programmes) {
        this.programmes = programmes;
    }




}


