package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Premises generated by hbm2java
 */
public class Premises  implements java.io.Serializable {


     private int premiseId;
     private String name;
     private String locationName;
     private String knownAs;
     private boolean primaryLocation;
     private boolean locationManaged;
     private int orgnisationId;
     private String locationStatus;
     private boolean stnetworkConectivity;
     private Date locationStatusDate;
     private String locationType;
     private String locationDescription;
     private String addressLine1;
     private String addressLine2;
     private String addressLine3;
     private String phoneNumber;
     private String postcode;
     private String faxNumber;
     private String cityTown;
     private String minicommNumber;
     private String county;
     private Boolean isNewShop;
     private String nation;
     private Date shopFlagDate;
     private boolean specialistShop;
     private String accreditations;
     private String jcpoffices;
     private boolean mediaContact;
     private Integer mediaContactId;
     private boolean cateringFacilities;
     private Integer cateringContactId;
     private Integer cateringType;
     private String localDemographicIssue;
     private Integer isnetwork;
     private boolean clientItfacilities;
     private String clientItfacilityDetails;
     private String localDemographicNotes;
     private boolean roomAvailability;
     private boolean volunteeringOpportunities;
     private String outreachLocation;
     private String localHotel;
     private String travelDetails;
     private Boolean visitorParkingOnsite;
     private String travelNearestBus;
     private Integer visitorParkingSpaces;
     private String travelNearestRail;
     private String travelNearestAirport;
     private String visitorParkingAlternative;
     private Boolean hostVisits;
     private Integer contactId;
     private Double roomOnlyRate;
     private Double negotiatedRoomOnlyRate;
     private Double bbrate;
     private Double bbnegotiatedRate;
     private Double dbbrate;
     private Double dbbnegotiatedRate;
     private Double ddrate;
     private Double ddnegotiatedRate;
     private Double rateDay;
     private Double negotiatedRateDay;
     private String teaAndCoffee;
     private Boolean lunch;
     private Date lastNegotiatedDate;
     private Date reNegotiatedOn;
     private Integer noOfMeetingRoom;
     private String preferedStatus;
     private Double meetingRoomRatePerDay;
     private String codings;
     private String comments;
     private String openTime;
     private boolean isActive;
     private Set servicePremises = new HashSet(0);

    public Premises() {
    }

	
    public Premises(int premiseId, String name, String locationName, boolean primaryLocation, boolean locationManaged, int orgnisationId, String locationStatus, boolean stnetworkConectivity, String locationType, String phoneNumber, boolean specialistShop, String accreditations, boolean mediaContact, boolean cateringFacilities, boolean clientItfacilities, boolean roomAvailability, boolean volunteeringOpportunities, boolean isActive) {
        this.premiseId = premiseId;
        this.name = name;
        this.locationName = locationName;
        this.primaryLocation = primaryLocation;
        this.locationManaged = locationManaged;
        this.orgnisationId = orgnisationId;
        this.locationStatus = locationStatus;
        this.stnetworkConectivity = stnetworkConectivity;
        this.locationType = locationType;
        this.phoneNumber = phoneNumber;
        this.specialistShop = specialistShop;
        this.accreditations = accreditations;
        this.mediaContact = mediaContact;
        this.cateringFacilities = cateringFacilities;
        this.clientItfacilities = clientItfacilities;
        this.roomAvailability = roomAvailability;
        this.volunteeringOpportunities = volunteeringOpportunities;
        this.isActive = isActive;
    }
    public Premises(int premiseId, String name, String locationName, String knownAs, boolean primaryLocation, boolean locationManaged, int orgnisationId, String locationStatus, boolean stnetworkConectivity, Date locationStatusDate, String locationType, String locationDescription, String addressLine1, String addressLine2, String addressLine3, String phoneNumber, String postcode, String faxNumber, String cityTown, String minicommNumber, String county, Boolean isNewShop, String nation, Date shopFlagDate, boolean specialistShop, String accreditations, String jcpoffices, boolean mediaContact, Integer mediaContactId, boolean cateringFacilities, Integer cateringContactId, Integer cateringType, String localDemographicIssue, Integer isnetwork, boolean clientItfacilities, String clientItfacilityDetails, String localDemographicNotes, boolean roomAvailability, boolean volunteeringOpportunities, String outreachLocation, String localHotel, String travelDetails, Boolean visitorParkingOnsite, String travelNearestBus, Integer visitorParkingSpaces, String travelNearestRail, String travelNearestAirport, String visitorParkingAlternative, Boolean hostVisits, Integer contactId, Double roomOnlyRate, Double negotiatedRoomOnlyRate, Double bbrate, Double bbnegotiatedRate, Double dbbrate, Double dbbnegotiatedRate, Double ddrate, Double ddnegotiatedRate, Double rateDay, Double negotiatedRateDay, String teaAndCoffee, Boolean lunch, Date lastNegotiatedDate, Date reNegotiatedOn, Integer noOfMeetingRoom, String preferedStatus, Double meetingRoomRatePerDay, String codings, String comments, String openTime, boolean isActive, Set servicePremises) {
       this.premiseId = premiseId;
       this.name = name;
       this.locationName = locationName;
       this.knownAs = knownAs;
       this.primaryLocation = primaryLocation;
       this.locationManaged = locationManaged;
       this.orgnisationId = orgnisationId;
       this.locationStatus = locationStatus;
       this.stnetworkConectivity = stnetworkConectivity;
       this.locationStatusDate = locationStatusDate;
       this.locationType = locationType;
       this.locationDescription = locationDescription;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.addressLine3 = addressLine3;
       this.phoneNumber = phoneNumber;
       this.postcode = postcode;
       this.faxNumber = faxNumber;
       this.cityTown = cityTown;
       this.minicommNumber = minicommNumber;
       this.county = county;
       this.isNewShop = isNewShop;
       this.nation = nation;
       this.shopFlagDate = shopFlagDate;
       this.specialistShop = specialistShop;
       this.accreditations = accreditations;
       this.jcpoffices = jcpoffices;
       this.mediaContact = mediaContact;
       this.mediaContactId = mediaContactId;
       this.cateringFacilities = cateringFacilities;
       this.cateringContactId = cateringContactId;
       this.cateringType = cateringType;
       this.localDemographicIssue = localDemographicIssue;
       this.isnetwork = isnetwork;
       this.clientItfacilities = clientItfacilities;
       this.clientItfacilityDetails = clientItfacilityDetails;
       this.localDemographicNotes = localDemographicNotes;
       this.roomAvailability = roomAvailability;
       this.volunteeringOpportunities = volunteeringOpportunities;
       this.outreachLocation = outreachLocation;
       this.localHotel = localHotel;
       this.travelDetails = travelDetails;
       this.visitorParkingOnsite = visitorParkingOnsite;
       this.travelNearestBus = travelNearestBus;
       this.visitorParkingSpaces = visitorParkingSpaces;
       this.travelNearestRail = travelNearestRail;
       this.travelNearestAirport = travelNearestAirport;
       this.visitorParkingAlternative = visitorParkingAlternative;
       this.hostVisits = hostVisits;
       this.contactId = contactId;
       this.roomOnlyRate = roomOnlyRate;
       this.negotiatedRoomOnlyRate = negotiatedRoomOnlyRate;
       this.bbrate = bbrate;
       this.bbnegotiatedRate = bbnegotiatedRate;
       this.dbbrate = dbbrate;
       this.dbbnegotiatedRate = dbbnegotiatedRate;
       this.ddrate = ddrate;
       this.ddnegotiatedRate = ddnegotiatedRate;
       this.rateDay = rateDay;
       this.negotiatedRateDay = negotiatedRateDay;
       this.teaAndCoffee = teaAndCoffee;
       this.lunch = lunch;
       this.lastNegotiatedDate = lastNegotiatedDate;
       this.reNegotiatedOn = reNegotiatedOn;
       this.noOfMeetingRoom = noOfMeetingRoom;
       this.preferedStatus = preferedStatus;
       this.meetingRoomRatePerDay = meetingRoomRatePerDay;
       this.codings = codings;
       this.comments = comments;
       this.openTime = openTime;
       this.isActive = isActive;
       this.servicePremises = servicePremises;
    }
   
    public int getPremiseId() {
        return this.premiseId;
    }
    
    public void setPremiseId(int premiseId) {
        this.premiseId = premiseId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public String getKnownAs() {
        return this.knownAs;
    }
    
    public void setKnownAs(String knownAs) {
        this.knownAs = knownAs;
    }
    public boolean isPrimaryLocation() {
        return this.primaryLocation;
    }
    
    public void setPrimaryLocation(boolean primaryLocation) {
        this.primaryLocation = primaryLocation;
    }
    public boolean isLocationManaged() {
        return this.locationManaged;
    }
    
    public void setLocationManaged(boolean locationManaged) {
        this.locationManaged = locationManaged;
    }
    public int getOrgnisationId() {
        return this.orgnisationId;
    }
    
    public void setOrgnisationId(int orgnisationId) {
        this.orgnisationId = orgnisationId;
    }
    public String getLocationStatus() {
        return this.locationStatus;
    }
    
    public void setLocationStatus(String locationStatus) {
        this.locationStatus = locationStatus;
    }
    public boolean isStnetworkConectivity() {
        return this.stnetworkConectivity;
    }
    
    public void setStnetworkConectivity(boolean stnetworkConectivity) {
        this.stnetworkConectivity = stnetworkConectivity;
    }
    public Date getLocationStatusDate() {
        return this.locationStatusDate;
    }
    
    public void setLocationStatusDate(Date locationStatusDate) {
        this.locationStatusDate = locationStatusDate;
    }
    public String getLocationType() {
        return this.locationType;
    }
    
    public void setLocationType(String locationType) {
        this.locationType = locationType;
    }
    public String getLocationDescription() {
        return this.locationDescription;
    }
    
    public void setLocationDescription(String locationDescription) {
        this.locationDescription = locationDescription;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getAddressLine3() {
        return this.addressLine3;
    }
    
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getFaxNumber() {
        return this.faxNumber;
    }
    
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }
    public String getCityTown() {
        return this.cityTown;
    }
    
    public void setCityTown(String cityTown) {
        this.cityTown = cityTown;
    }
    public String getMinicommNumber() {
        return this.minicommNumber;
    }
    
    public void setMinicommNumber(String minicommNumber) {
        this.minicommNumber = minicommNumber;
    }
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }
    public Boolean getIsNewShop() {
        return this.isNewShop;
    }
    
    public void setIsNewShop(Boolean isNewShop) {
        this.isNewShop = isNewShop;
    }
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }
    public Date getShopFlagDate() {
        return this.shopFlagDate;
    }
    
    public void setShopFlagDate(Date shopFlagDate) {
        this.shopFlagDate = shopFlagDate;
    }
    public boolean isSpecialistShop() {
        return this.specialistShop;
    }
    
    public void setSpecialistShop(boolean specialistShop) {
        this.specialistShop = specialistShop;
    }
    public String getAccreditations() {
        return this.accreditations;
    }
    
    public void setAccreditations(String accreditations) {
        this.accreditations = accreditations;
    }
    public String getJcpoffices() {
        return this.jcpoffices;
    }
    
    public void setJcpoffices(String jcpoffices) {
        this.jcpoffices = jcpoffices;
    }
    public boolean isMediaContact() {
        return this.mediaContact;
    }
    
    public void setMediaContact(boolean mediaContact) {
        this.mediaContact = mediaContact;
    }
    public Integer getMediaContactId() {
        return this.mediaContactId;
    }
    
    public void setMediaContactId(Integer mediaContactId) {
        this.mediaContactId = mediaContactId;
    }
    public boolean isCateringFacilities() {
        return this.cateringFacilities;
    }
    
    public void setCateringFacilities(boolean cateringFacilities) {
        this.cateringFacilities = cateringFacilities;
    }
    public Integer getCateringContactId() {
        return this.cateringContactId;
    }
    
    public void setCateringContactId(Integer cateringContactId) {
        this.cateringContactId = cateringContactId;
    }
    public Integer getCateringType() {
        return this.cateringType;
    }
    
    public void setCateringType(Integer cateringType) {
        this.cateringType = cateringType;
    }
    public String getLocalDemographicIssue() {
        return this.localDemographicIssue;
    }
    
    public void setLocalDemographicIssue(String localDemographicIssue) {
        this.localDemographicIssue = localDemographicIssue;
    }
    public Integer getIsnetwork() {
        return this.isnetwork;
    }
    
    public void setIsnetwork(Integer isnetwork) {
        this.isnetwork = isnetwork;
    }
    public boolean isClientItfacilities() {
        return this.clientItfacilities;
    }
    
    public void setClientItfacilities(boolean clientItfacilities) {
        this.clientItfacilities = clientItfacilities;
    }
    public String getClientItfacilityDetails() {
        return this.clientItfacilityDetails;
    }
    
    public void setClientItfacilityDetails(String clientItfacilityDetails) {
        this.clientItfacilityDetails = clientItfacilityDetails;
    }
    public String getLocalDemographicNotes() {
        return this.localDemographicNotes;
    }
    
    public void setLocalDemographicNotes(String localDemographicNotes) {
        this.localDemographicNotes = localDemographicNotes;
    }
    public boolean isRoomAvailability() {
        return this.roomAvailability;
    }
    
    public void setRoomAvailability(boolean roomAvailability) {
        this.roomAvailability = roomAvailability;
    }
    public boolean isVolunteeringOpportunities() {
        return this.volunteeringOpportunities;
    }
    
    public void setVolunteeringOpportunities(boolean volunteeringOpportunities) {
        this.volunteeringOpportunities = volunteeringOpportunities;
    }
    public String getOutreachLocation() {
        return this.outreachLocation;
    }
    
    public void setOutreachLocation(String outreachLocation) {
        this.outreachLocation = outreachLocation;
    }
    public String getLocalHotel() {
        return this.localHotel;
    }
    
    public void setLocalHotel(String localHotel) {
        this.localHotel = localHotel;
    }
    public String getTravelDetails() {
        return this.travelDetails;
    }
    
    public void setTravelDetails(String travelDetails) {
        this.travelDetails = travelDetails;
    }
    public Boolean getVisitorParkingOnsite() {
        return this.visitorParkingOnsite;
    }
    
    public void setVisitorParkingOnsite(Boolean visitorParkingOnsite) {
        this.visitorParkingOnsite = visitorParkingOnsite;
    }
    public String getTravelNearestBus() {
        return this.travelNearestBus;
    }
    
    public void setTravelNearestBus(String travelNearestBus) {
        this.travelNearestBus = travelNearestBus;
    }
    public Integer getVisitorParkingSpaces() {
        return this.visitorParkingSpaces;
    }
    
    public void setVisitorParkingSpaces(Integer visitorParkingSpaces) {
        this.visitorParkingSpaces = visitorParkingSpaces;
    }
    public String getTravelNearestRail() {
        return this.travelNearestRail;
    }
    
    public void setTravelNearestRail(String travelNearestRail) {
        this.travelNearestRail = travelNearestRail;
    }
    public String getTravelNearestAirport() {
        return this.travelNearestAirport;
    }
    
    public void setTravelNearestAirport(String travelNearestAirport) {
        this.travelNearestAirport = travelNearestAirport;
    }
    public String getVisitorParkingAlternative() {
        return this.visitorParkingAlternative;
    }
    
    public void setVisitorParkingAlternative(String visitorParkingAlternative) {
        this.visitorParkingAlternative = visitorParkingAlternative;
    }
    public Boolean getHostVisits() {
        return this.hostVisits;
    }
    
    public void setHostVisits(Boolean hostVisits) {
        this.hostVisits = hostVisits;
    }
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
    public Double getRoomOnlyRate() {
        return this.roomOnlyRate;
    }
    
    public void setRoomOnlyRate(Double roomOnlyRate) {
        this.roomOnlyRate = roomOnlyRate;
    }
    public Double getNegotiatedRoomOnlyRate() {
        return this.negotiatedRoomOnlyRate;
    }
    
    public void setNegotiatedRoomOnlyRate(Double negotiatedRoomOnlyRate) {
        this.negotiatedRoomOnlyRate = negotiatedRoomOnlyRate;
    }
    public Double getBbrate() {
        return this.bbrate;
    }
    
    public void setBbrate(Double bbrate) {
        this.bbrate = bbrate;
    }
    public Double getBbnegotiatedRate() {
        return this.bbnegotiatedRate;
    }
    
    public void setBbnegotiatedRate(Double bbnegotiatedRate) {
        this.bbnegotiatedRate = bbnegotiatedRate;
    }
    public Double getDbbrate() {
        return this.dbbrate;
    }
    
    public void setDbbrate(Double dbbrate) {
        this.dbbrate = dbbrate;
    }
    public Double getDbbnegotiatedRate() {
        return this.dbbnegotiatedRate;
    }
    
    public void setDbbnegotiatedRate(Double dbbnegotiatedRate) {
        this.dbbnegotiatedRate = dbbnegotiatedRate;
    }
    public Double getDdrate() {
        return this.ddrate;
    }
    
    public void setDdrate(Double ddrate) {
        this.ddrate = ddrate;
    }
    public Double getDdnegotiatedRate() {
        return this.ddnegotiatedRate;
    }
    
    public void setDdnegotiatedRate(Double ddnegotiatedRate) {
        this.ddnegotiatedRate = ddnegotiatedRate;
    }
    public Double getRateDay() {
        return this.rateDay;
    }
    
    public void setRateDay(Double rateDay) {
        this.rateDay = rateDay;
    }
    public Double getNegotiatedRateDay() {
        return this.negotiatedRateDay;
    }
    
    public void setNegotiatedRateDay(Double negotiatedRateDay) {
        this.negotiatedRateDay = negotiatedRateDay;
    }
    public String getTeaAndCoffee() {
        return this.teaAndCoffee;
    }
    
    public void setTeaAndCoffee(String teaAndCoffee) {
        this.teaAndCoffee = teaAndCoffee;
    }
    public Boolean getLunch() {
        return this.lunch;
    }
    
    public void setLunch(Boolean lunch) {
        this.lunch = lunch;
    }
    public Date getLastNegotiatedDate() {
        return this.lastNegotiatedDate;
    }
    
    public void setLastNegotiatedDate(Date lastNegotiatedDate) {
        this.lastNegotiatedDate = lastNegotiatedDate;
    }
    public Date getReNegotiatedOn() {
        return this.reNegotiatedOn;
    }
    
    public void setReNegotiatedOn(Date reNegotiatedOn) {
        this.reNegotiatedOn = reNegotiatedOn;
    }
    public Integer getNoOfMeetingRoom() {
        return this.noOfMeetingRoom;
    }
    
    public void setNoOfMeetingRoom(Integer noOfMeetingRoom) {
        this.noOfMeetingRoom = noOfMeetingRoom;
    }
    public String getPreferedStatus() {
        return this.preferedStatus;
    }
    
    public void setPreferedStatus(String preferedStatus) {
        this.preferedStatus = preferedStatus;
    }
    public Double getMeetingRoomRatePerDay() {
        return this.meetingRoomRatePerDay;
    }
    
    public void setMeetingRoomRatePerDay(Double meetingRoomRatePerDay) {
        this.meetingRoomRatePerDay = meetingRoomRatePerDay;
    }
    public String getCodings() {
        return this.codings;
    }
    
    public void setCodings(String codings) {
        this.codings = codings;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getOpenTime() {
        return this.openTime;
    }
    
    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getServicePremises() {
        return this.servicePremises;
    }
    
    public void setServicePremises(Set servicePremises) {
        this.servicePremises = servicePremises;
    }




}


