package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Programmes generated by hbm2java
 */
public class Programmes  implements java.io.Serializable {


     private int programmeId;
     private Contacts contacts;
     private String name;
     private String description;
     private boolean isActive;
     private Set organisationProgrammes = new HashSet(0);

    public Programmes() {
    }

	
    public Programmes(int programmeId, String name, boolean isActive) {
        this.programmeId = programmeId;
        this.name = name;
        this.isActive = isActive;
    }
    public Programmes(int programmeId, Contacts contacts, String name, String description, boolean isActive, Set organisationProgrammes) {
       this.programmeId = programmeId;
       this.contacts = contacts;
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.organisationProgrammes = organisationProgrammes;
    }
   
    public int getProgrammeId() {
        return this.programmeId;
    }
    
    public void setProgrammeId(int programmeId) {
        this.programmeId = programmeId;
    }
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getOrganisationProgrammes() {
        return this.organisationProgrammes;
    }
    
    public void setOrganisationProgrammes(Set organisationProgrammes) {
        this.organisationProgrammes = organisationProgrammes;
    }




}


