package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SupportingMaterials generated by hbm2java
 */
public class SupportingMaterials  implements java.io.Serializable {


     private int supportingMaterialId;
     private Organisations organisations;
     private Users users;
     private String url;
     private String description;
     private String type;
     private Date addedDate;
     private boolean isActive;

    public SupportingMaterials() {
    }

	
    public SupportingMaterials(int supportingMaterialId, Organisations organisations, Users users, String url, Date addedDate, boolean isActive) {
        this.supportingMaterialId = supportingMaterialId;
        this.organisations = organisations;
        this.users = users;
        this.url = url;
        this.addedDate = addedDate;
        this.isActive = isActive;
    }
    public SupportingMaterials(int supportingMaterialId, Organisations organisations, Users users, String url, String description, String type, Date addedDate, boolean isActive) {
       this.supportingMaterialId = supportingMaterialId;
       this.organisations = organisations;
       this.users = users;
       this.url = url;
       this.description = description;
       this.type = type;
       this.addedDate = addedDate;
       this.isActive = isActive;
    }
   
    public int getSupportingMaterialId() {
        return this.supportingMaterialId;
    }
    
    public void setSupportingMaterialId(int supportingMaterialId) {
        this.supportingMaterialId = supportingMaterialId;
    }
    public Organisations getOrganisations() {
        return this.organisations;
    }
    
    public void setOrganisations(Organisations organisations) {
        this.organisations = organisations;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


