package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Towns generated by hbm2java
 */
public class Towns  implements java.io.Serializable {


     private int townId;
     private Counties counties;
     private String name;
     private Set addresseses = new HashSet(0);

    public Towns() {
    }

	
    public Towns(int townId, Counties counties) {
        this.townId = townId;
        this.counties = counties;
    }
    public Towns(int townId, Counties counties, String name, Set addresseses) {
       this.townId = townId;
       this.counties = counties;
       this.name = name;
       this.addresseses = addresseses;
    }
   
    public int getTownId() {
        return this.townId;
    }
    
    public void setTownId(int townId) {
        this.townId = townId;
    }
    public Counties getCounties() {
        return this.counties;
    }
    
    public void setCounties(Counties counties) {
        this.counties = counties;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set addresseses) {
        this.addresseses = addresseses;
    }




}


