package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TrustDistricts generated by hbm2java
 */
public class TrustDistricts  implements java.io.Serializable {


     private int trustDistrictId;
     private TrustRegions trustRegions;
     private String name;
     private String description;
     private boolean isActive;
     private Set organisationses = new HashSet(0);

    public TrustDistricts() {
    }

	
    public TrustDistricts(int trustDistrictId, TrustRegions trustRegions, String name, boolean isActive) {
        this.trustDistrictId = trustDistrictId;
        this.trustRegions = trustRegions;
        this.name = name;
        this.isActive = isActive;
    }
    public TrustDistricts(int trustDistrictId, TrustRegions trustRegions, String name, String description, boolean isActive, Set organisationses) {
       this.trustDistrictId = trustDistrictId;
       this.trustRegions = trustRegions;
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.organisationses = organisationses;
    }
   
    public int getTrustDistrictId() {
        return this.trustDistrictId;
    }
    
    public void setTrustDistrictId(int trustDistrictId) {
        this.trustDistrictId = trustDistrictId;
    }
    public TrustRegions getTrustRegions() {
        return this.trustRegions;
    }
    
    public void setTrustRegions(TrustRegions trustRegions) {
        this.trustRegions = trustRegions;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getOrganisationses() {
        return this.organisationses;
    }
    
    public void setOrganisationses(Set organisationses) {
        this.organisationses = organisationses;
    }




}


