package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Volunteers generated by hbm2java
 */
public class Volunteers  implements java.io.Serializable {


     private int volunteerId;
     private Contacts contacts;
     private String volunteerPurpose;
     private String details;
     private Date startDate;
     private Date endDate;
     private Integer premiseId;
     private int volunteerNo;
     private boolean isActive;

    public Volunteers() {
    }

	
    public Volunteers(int volunteerId, Contacts contacts, int volunteerNo, boolean isActive) {
        this.volunteerId = volunteerId;
        this.contacts = contacts;
        this.volunteerNo = volunteerNo;
        this.isActive = isActive;
    }
    public Volunteers(int volunteerId, Contacts contacts, String volunteerPurpose, String details, Date startDate, Date endDate, Integer premiseId, int volunteerNo, boolean isActive) {
       this.volunteerId = volunteerId;
       this.contacts = contacts;
       this.volunteerPurpose = volunteerPurpose;
       this.details = details;
       this.startDate = startDate;
       this.endDate = endDate;
       this.premiseId = premiseId;
       this.volunteerNo = volunteerNo;
       this.isActive = isActive;
    }
   
    public int getVolunteerId() {
        return this.volunteerId;
    }
    
    public void setVolunteerId(int volunteerId) {
        this.volunteerId = volunteerId;
    }
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }
    public String getVolunteerPurpose() {
        return this.volunteerPurpose;
    }
    
    public void setVolunteerPurpose(String volunteerPurpose) {
        this.volunteerPurpose = volunteerPurpose;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getPremiseId() {
        return this.premiseId;
    }
    
    public void setPremiseId(Integer premiseId) {
        this.premiseId = premiseId;
    }
    public int getVolunteerNo() {
        return this.volunteerNo;
    }
    
    public void setVolunteerNo(int volunteerNo) {
        this.volunteerNo = volunteerNo;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


