package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Directorate generated by hbm2java
 */
public class Directorate implements java.io.Serializable {

	private int directorateId;
	private Contact contact;
	private Organisation organisation;
	private TypeOfBusiness typeOfBusiness;
	private County county;
	private String name;
	private String shortDesc;
	private Boolean copyAddrOrg;
	private String addr1;
	private String addr2;
	private String addr3;
	private String postCode;
	private String town;
	private String fullDesc;
	private String phoneNumber;
	private String fax;
	private String email;
	private String webAddr;
	private String charityNumber;
	private String companyNumber;
	private Boolean status;
	private Set<Department> departments = new HashSet<Department>(0);

	public Directorate() {
	}

	public Directorate(int directorateId) {
		this.directorateId = directorateId;
	}

	public Directorate(int directorateId, Contact contact,
			Organisation organisation, TypeOfBusiness typeOfBusiness,
			County county, String name, String shortDesc, Boolean copyAddrOrg,
			String addr1, String addr2, String addr3, String postCode,
			String town, String fullDesc, String phoneNumber, String fax,
			String email, String webAddr, String charityNumber,
			String companyNumber, Boolean status, Set<Department> departments) {
		this.directorateId = directorateId;
		this.contact = contact;
		this.organisation = organisation;
		this.typeOfBusiness = typeOfBusiness;
		this.county = county;
		this.name = name;
		this.shortDesc = shortDesc;
		this.copyAddrOrg = copyAddrOrg;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.postCode = postCode;
		this.town = town;
		this.fullDesc = fullDesc;
		this.phoneNumber = phoneNumber;
		this.fax = fax;
		this.email = email;
		this.webAddr = webAddr;
		this.charityNumber = charityNumber;
		this.companyNumber = companyNumber;
		this.status = status;
		this.departments = departments;
	}

	public int getDirectorateId() {
		return this.directorateId;
	}

	public void setDirectorateId(int directorateId) {
		this.directorateId = directorateId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	public TypeOfBusiness getTypeOfBusiness() {
		return this.typeOfBusiness;
	}

	public void setTypeOfBusiness(TypeOfBusiness typeOfBusiness) {
		this.typeOfBusiness = typeOfBusiness;
	}

	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public Boolean getCopyAddrOrg() {
		return this.copyAddrOrg;
	}

	public void setCopyAddrOrg(Boolean copyAddrOrg) {
		this.copyAddrOrg = copyAddrOrg;
	}

	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getFullDesc() {
		return this.fullDesc;
	}

	public void setFullDesc(String fullDesc) {
		this.fullDesc = fullDesc;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebAddr() {
		return this.webAddr;
	}

	public void setWebAddr(String webAddr) {
		this.webAddr = webAddr;
	}

	public String getCharityNumber() {
		return this.charityNumber;
	}

	public void setCharityNumber(String charityNumber) {
		this.charityNumber = charityNumber;
	}

	public String getCompanyNumber() {
		return this.companyNumber;
	}

	public void setCompanyNumber(String companyNumber) {
		this.companyNumber = companyNumber;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

}
