package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GovOfficeRegion generated by hbm2java
 */
public class GovOfficeRegion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int govOfficeRegionId;
	private County county;
	private String name;
	private String description;
	private Boolean status;
	private Set<Organisation> organisations = new HashSet<Organisation>(0);

	public GovOfficeRegion() {
	}

	public GovOfficeRegion(int govOfficeRegionId) {
		this.govOfficeRegionId = govOfficeRegionId;
	}

	public GovOfficeRegion(int govOfficeRegionId, County county, String name,
			String description, Boolean status, Set<Organisation> organisations) {
		this.govOfficeRegionId = govOfficeRegionId;
		this.county = county;
		this.name = name;
		this.description = description;
		this.status = status;
		this.organisations = organisations;
	}

	public int getGovOfficeRegionId() {
		return this.govOfficeRegionId;
	}

	public void setGovOfficeRegionId(int govOfficeRegionId) {
		this.govOfficeRegionId = govOfficeRegionId;
	}

	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

}
