package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * SupportingMaterial generated by hbm2java
 */
public class SupportingMaterial implements java.io.Serializable {

	private int supportingMaterialId;
	private Account account;
	private Organisation organisation;
	private String url;
	private String description;
	private String type;
	private Date addedDate;
	private Boolean status;

	public SupportingMaterial() {
	}

	public SupportingMaterial(int supportingMaterialId) {
		this.supportingMaterialId = supportingMaterialId;
	}

	public SupportingMaterial(int supportingMaterialId, Account account,
			Organisation organisation, String url, String description,
			String type, Date addedDate, Boolean status) {
		this.supportingMaterialId = supportingMaterialId;
		this.account = account;
		this.organisation = organisation;
		this.url = url;
		this.description = description;
		this.type = type;
		this.addedDate = addedDate;
		this.status = status;
	}

	public int getSupportingMaterialId() {
		return this.supportingMaterialId;
	}

	public void setSupportingMaterialId(int supportingMaterialId) {
		this.supportingMaterialId = supportingMaterialId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
