package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int accountId;
	private String userName;
	private String password;
	private String email;
	private Integer permission;
	private Set<SupportingMaterial> supportingMaterials = new HashSet<SupportingMaterial>(
			0);

	public Account() {
	}

	public Account(int accountId) {
		this.accountId = accountId;
	}

	public Account(int accountId, String userName, String password,
			String email, Integer permission,
			Set<SupportingMaterial> supportingMaterials) {
		this.accountId = accountId;
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.permission = permission;
		this.supportingMaterials = supportingMaterials;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getPermission() {
		return this.permission;
	}

	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	public Set<SupportingMaterial> getSupportingMaterials() {
		return this.supportingMaterials;
	}

	public void setSupportingMaterials(
			Set<SupportingMaterial> supportingMaterials) {
		this.supportingMaterials = supportingMaterials;
	}

}
