package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int contactId;
	private ReferenceData referenceDataByBestContactMethod;
	private ReferenceData referenceDataByContactType;
	private String firstName;
	private String surName;
	private String knowAs;
	private String officePhone;
	private String mobilePhone;
	private String sthomePhone;
	private String emailAddress;
	private Integer managerId;
	private String jobRole;
	private String workBase;
	private String jobTitle;
	private Boolean status;
	private Set<Facility> facilitiesForContactId = new HashSet<Facility>(0);
	private Set<Organisation> organisations = new HashSet<Organisation>(0);
	private Set<Team> teams = new HashSet<Team>(0);
	private Set<Volunteer> volunteers = new HashSet<Volunteer>(0);
	private Set<Facility> facilitiesForRoomHost = new HashSet<Facility>(0);
	private Set<Department> departments = new HashSet<Department>(0);
	private Set<Directorate> directorates = new HashSet<Directorate>(0);
	private Set<Service> services = new HashSet<Service>(0);
	private Set<Programme> programmes = new HashSet<Programme>(0);

	public Contact() {
	}

	public Contact(int contactId) {
		this.contactId = contactId;
	}

	public Contact(int contactId,
			ReferenceData referenceDataByBestContactMethod,
			ReferenceData referenceDataByContactType, String firstName,
			String surName, String knowAs, String officePhone,
			String mobilePhone, String sthomePhone, String emailAddress,
			Integer managerId, String jobRole, String workBase,
			String jobTitle, Boolean status,
			Set<Facility> facilitiesForContactId,
			Set<Organisation> organisations, Set<Team> teams,
			Set<Volunteer> volunteers, Set<Facility> facilitiesForRoomHost,
			Set<Department> departments, Set<Directorate> directorates,
			Set<Service> services, Set<Programme> programmes) {
		this.contactId = contactId;
		this.referenceDataByBestContactMethod = referenceDataByBestContactMethod;
		this.referenceDataByContactType = referenceDataByContactType;
		this.firstName = firstName;
		this.surName = surName;
		this.knowAs = knowAs;
		this.officePhone = officePhone;
		this.mobilePhone = mobilePhone;
		this.sthomePhone = sthomePhone;
		this.emailAddress = emailAddress;
		this.managerId = managerId;
		this.jobRole = jobRole;
		this.workBase = workBase;
		this.jobTitle = jobTitle;
		this.status = status;
		this.facilitiesForContactId = facilitiesForContactId;
		this.organisations = organisations;
		this.teams = teams;
		this.volunteers = volunteers;
		this.facilitiesForRoomHost = facilitiesForRoomHost;
		this.departments = departments;
		this.directorates = directorates;
		this.services = services;
		this.programmes = programmes;
	}

	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public ReferenceData getReferenceDataByBestContactMethod() {
		return this.referenceDataByBestContactMethod;
	}

	public void setReferenceDataByBestContactMethod(
			ReferenceData referenceDataByBestContactMethod) {
		this.referenceDataByBestContactMethod = referenceDataByBestContactMethod;
	}

	public ReferenceData getReferenceDataByContactType() {
		return this.referenceDataByContactType;
	}

	public void setReferenceDataByContactType(
			ReferenceData referenceDataByContactType) {
		this.referenceDataByContactType = referenceDataByContactType;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurName() {
		return this.surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	public String getKnowAs() {
		return this.knowAs;
	}

	public void setKnowAs(String knowAs) {
		this.knowAs = knowAs;
	}

	public String getOfficePhone() {
		return this.officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getSthomePhone() {
		return this.sthomePhone;
	}

	public void setSthomePhone(String sthomePhone) {
		this.sthomePhone = sthomePhone;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Integer getManagerId() {
		return this.managerId;
	}

	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	public String getJobRole() {
		return this.jobRole;
	}

	public void setJobRole(String jobRole) {
		this.jobRole = jobRole;
	}

	public String getWorkBase() {
		return this.workBase;
	}

	public void setWorkBase(String workBase) {
		this.workBase = workBase;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<Facility> getFacilitiesForContactId() {
		return this.facilitiesForContactId;
	}

	public void setFacilitiesForContactId(Set<Facility> facilitiesForContactId) {
		this.facilitiesForContactId = facilitiesForContactId;
	}

	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

	public Set<Volunteer> getVolunteers() {
		return this.volunteers;
	}

	public void setVolunteers(Set<Volunteer> volunteers) {
		this.volunteers = volunteers;
	}

	public Set<Facility> getFacilitiesForRoomHost() {
		return this.facilitiesForRoomHost;
	}

	public void setFacilitiesForRoomHost(Set<Facility> facilitiesForRoomHost) {
		this.facilitiesForRoomHost = facilitiesForRoomHost;
	}

	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

	public Set<Directorate> getDirectorates() {
		return this.directorates;
	}

	public void setDirectorates(Set<Directorate> directorates) {
		this.directorates = directorates;
	}

	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

	public Set<Programme> getProgrammes() {
		return this.programmes;
	}

	public void setProgrammes(Set<Programme> programmes) {
		this.programmes = programmes;
	}

}
