package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Contacts generated by hbm2java
 */
public class Contacts implements java.io.Serializable {

	/**
	 * 
	 */
	private int contactId;
	private ReferenceData referenceData;
	private String firstName;
	private String surName;
	private String knowAs;
	private String officePhone;
	private String mobilePhone;
	private String sthomePhone;
	private String emailAddress;
	private Integer managerId;
	private String bestContactMethod;
	private String jobRole;
	private String workBase;
	private String jobTitle;
	private Boolean isActive;
	private Set<Organisations> organisationses = new HashSet<Organisations>(0);
	private Set<Programmes> programmeses = new HashSet<Programmes>(0);
	private Set<Directorates> directorateses = new HashSet<Directorates>(0);
	private Set<Facilities> facilitieses = new HashSet<Facilities>(0);
	private Set<Teams> teamses = new HashSet<Teams>(0);
	private Set<Volunteers> volunteerses = new HashSet<Volunteers>(0);

	public Contacts() {
	}

	public Contacts(int contactId) {
		this.contactId = contactId;
	}

	public Contacts(int contactId, ReferenceData referenceData,
			String firstName, String surName, String knowAs,
			String officePhone, String mobilePhone, String sthomePhone,
			String emailAddress, Integer managerId, String bestContactMethod,
			String jobRole, String workBase, String jobTitle, Boolean isActive,
			Set<Organisations> organisationses, Set<Programmes> programmeses,
			Set<Directorates> directorateses, Set<Facilities> facilitieses,
			Set<Teams> teamses, Set<Volunteers> volunteerses) {
		super();
		this.contactId = contactId;
		this.referenceData = referenceData;
		this.firstName = firstName;
		this.surName = surName;
		this.knowAs = knowAs;
		this.officePhone = officePhone;
		this.mobilePhone = mobilePhone;
		this.sthomePhone = sthomePhone;
		this.emailAddress = emailAddress;
		this.managerId = managerId;
		this.bestContactMethod = bestContactMethod;
		this.jobRole = jobRole;
		this.workBase = workBase;
		this.jobTitle = jobTitle;
		this.isActive = isActive;
		this.organisationses = organisationses;
		this.programmeses = programmeses;
		this.directorateses = directorateses;
		this.facilitieses = facilitieses;
		this.teamses = teamses;
		this.volunteerses = volunteerses;
	}

	public int getContactId() {
		return contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public ReferenceData getReferenceData() {
		return referenceData;
	}

	public void setReferenceData(ReferenceData referenceData) {
		this.referenceData = referenceData;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurName() {
		return surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	public String getKnowAs() {
		return knowAs;
	}

	public void setKnowAs(String knowAs) {
		this.knowAs = knowAs;
	}

	public String getOfficePhone() {
		return officePhone;
	}

	public void setOfficePhone(String officePhone) {
		this.officePhone = officePhone;
	}

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getSthomePhone() {
		return sthomePhone;
	}

	public void setSthomePhone(String sthomePhone) {
		this.sthomePhone = sthomePhone;
	}

	public String getEmailAddress() {
		return emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Integer getManagerId() {
		return managerId;
	}

	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	public String getBestContactMethod() {
		return bestContactMethod;
	}

	public void setBestContactMethod(String bestContactMethod) {
		this.bestContactMethod = bestContactMethod;
	}

	public String getJobRole() {
		return jobRole;
	}

	public void setJobRole(String jobRole) {
		this.jobRole = jobRole;
	}

	public String getWorkBase() {
		return workBase;
	}

	public void setWorkBase(String workBase) {
		this.workBase = workBase;
	}

	public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<Organisations> getOrganisationses() {
		return organisationses;
	}

	public void setOrganisationses(Set<Organisations> organisationses) {
		this.organisationses = organisationses;
	}

	public Set<Programmes> getProgrammeses() {
		return programmeses;
	}

	public void setProgrammeses(Set<Programmes> programmeses) {
		this.programmeses = programmeses;
	}

	public Set<Directorates> getDirectorateses() {
		return directorateses;
	}

	public void setDirectorateses(Set<Directorates> directorateses) {
		this.directorateses = directorateses;
	}

	public Set<Facilities> getFacilitieses() {
		return facilitieses;
	}

	public void setFacilitieses(Set<Facilities> facilitieses) {
		this.facilitieses = facilitieses;
	}

	public Set<Teams> getTeamses() {
		return teamses;
	}

	public void setTeamses(Set<Teams> teamses) {
		this.teamses = teamses;
	}

	public Set<Volunteers> getVolunteerses() {
		return volunteerses;
	}

	public void setVolunteerses(Set<Volunteers> volunteerses) {
		this.volunteerses = volunteerses;
	}

}
