package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Counties generated by hbm2java
 */
public class Counties  implements java.io.Serializable {


     private int countyId;
     private Countries countries;
     private String name;
     private Set govtOfficeRegionses = new HashSet(0);
     private Set townses = new HashSet(0);

    public Counties() {
    }

	
    public Counties(int countyId, Countries countries, String name) {
        this.countyId = countyId;
        this.countries = countries;
        this.name = name;
    }
    public Counties(int countyId, Countries countries, String name, Set govtOfficeRegionses, Set townses) {
       this.countyId = countyId;
       this.countries = countries;
       this.name = name;
       this.govtOfficeRegionses = govtOfficeRegionses;
       this.townses = townses;
    }
   
    public int getCountyId() {
        return this.countyId;
    }
    
    public void setCountyId(int countyId) {
        this.countyId = countyId;
    }
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getGovtOfficeRegionses() {
        return this.govtOfficeRegionses;
    }
    
    public void setGovtOfficeRegionses(Set govtOfficeRegionses) {
        this.govtOfficeRegionses = govtOfficeRegionses;
    }
    public Set getTownses() {
        return this.townses;
    }
    
    public void setTownses(Set townses) {
        this.townses = townses;
    }




}


