package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Countries generated by hbm2java
 */
public class Countries  implements java.io.Serializable {


     private int countryId;
     private String name;
     private Set countieses = new HashSet(0);
     private Set trustRegionses = new HashSet(0);

    public Countries() {
    }

	
    public Countries(int countryId, String name) {
        this.countryId = countryId;
        this.name = name;
    }
    public Countries(int countryId, String name, Set countieses, Set trustRegionses) {
       this.countryId = countryId;
       this.name = name;
       this.countieses = countieses;
       this.trustRegionses = trustRegionses;
    }
   
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCountieses() {
        return this.countieses;
    }
    
    public void setCountieses(Set countieses) {
        this.countieses = countieses;
    }
    public Set getTrustRegionses() {
        return this.trustRegionses;
    }
    
    public void setTrustRegionses(Set trustRegionses) {
        this.trustRegionses = trustRegionses;
    }




}


