package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Countries generated by hbm2java
 */
public class Countries implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int countryId;
	private String name;
	private Set<Counties> countieses = new HashSet<Counties>(0);
	private Set<TrustRegions> trustRegionses = new HashSet<TrustRegions>(0);

	public Countries() {
	}

	public Countries(int countryId) {
		this.countryId = countryId;
	}

	public Countries(int countryId, String name, Set<Counties> countieses,
			Set<TrustRegions> trustRegionses) {
		this.countryId = countryId;
		this.name = name;
		this.countieses = countieses;
		this.trustRegionses = trustRegionses;
	}

	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Counties> getCountieses() {
		return this.countieses;
	}

	public void setCountieses(Set<Counties> countieses) {
		this.countieses = countieses;
	}

	public Set<TrustRegions> getTrustRegionses() {
		return this.trustRegionses;
	}

	public void setTrustRegionses(Set<TrustRegions> trustRegionses) {
		this.trustRegionses = trustRegionses;
	}

}
