package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private int countryId;
	private String name;
	private Set<TrustRegion> trustRegions = new HashSet<TrustRegion>(0);
	private Set<Premise> premises = new HashSet<Premise>(0);
	private Set<County> counties = new HashSet<County>(0);

	public Country() {
	}

	public Country(int countryId) {
		this.countryId = countryId;
	}

	public Country(int countryId, String name, Set<TrustRegion> trustRegions,
			Set<Premise> premises, Set<County> counties) {
		this.countryId = countryId;
		this.name = name;
		this.trustRegions = trustRegions;
		this.premises = premises;
		this.counties = counties;
	}

	public int getCountryId() {
		return this.countryId;
	}

	public void setCountryId(int countryId) {
		this.countryId = countryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<TrustRegion> getTrustRegions() {
		return this.trustRegions;
	}

	public void setTrustRegions(Set<TrustRegion> trustRegions) {
		this.trustRegions = trustRegions;
	}

	public Set<Premise> getPremises() {
		return this.premises;
	}

	public void setPremises(Set<Premise> premises) {
		this.premises = premises;
	}

	public Set<County> getCounties() {
		return this.counties;
	}

	public void setCounties(Set<County> counties) {
		this.counties = counties;
	}

}
