package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int departmentId;
	private Contact contact;
	private TypeOfBusiness typeOfBusiness;
	private Directorate directorate;
	private String name;
	private String shortDesc;
	private Boolean copyAddr;
	private String addr1;
	private String addr2;
	private String addr3;
	private String postCode;
	private String town;
	private Integer countyId;
	private String fullDesc;
	private String phoneNumber;
	private String fax;
	private String email;
	private String webAddr;
	private boolean status;
	private Set<Team> teams = new HashSet<Team>(0);

	public Department() {
	}

	public Department(int departmentId, Directorate directorate, boolean status) {
		this.departmentId = departmentId;
		this.directorate = directorate;
		this.status = status;
	}

	public Department(int departmentId, Contact contact,
			TypeOfBusiness typeOfBusiness, Directorate directorate,
			String name, String shortDesc, Boolean copyAddr, String addr1,
			String addr2, String addr3, String postCode, String town,
			Integer countyId, String fullDesc, String phoneNumber, String fax,
			String email, String webAddr, boolean status, Set<Team> teams) {
		this.departmentId = departmentId;
		this.contact = contact;
		this.typeOfBusiness = typeOfBusiness;
		this.directorate = directorate;
		this.name = name;
		this.shortDesc = shortDesc;
		this.copyAddr = copyAddr;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.postCode = postCode;
		this.town = town;
		this.countyId = countyId;
		this.fullDesc = fullDesc;
		this.phoneNumber = phoneNumber;
		this.fax = fax;
		this.email = email;
		this.webAddr = webAddr;
		this.status = status;
		this.teams = teams;
	}

	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public TypeOfBusiness getTypeOfBusiness() {
		return this.typeOfBusiness;
	}

	public void setTypeOfBusiness(TypeOfBusiness typeOfBusiness) {
		this.typeOfBusiness = typeOfBusiness;
	}

	public Directorate getDirectorate() {
		return this.directorate;
	}

	public void setDirectorate(Directorate directorate) {
		this.directorate = directorate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public Boolean getCopyAddr() {
		return this.copyAddr;
	}

	public void setCopyAddr(Boolean copyAddr) {
		this.copyAddr = copyAddr;
	}

	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public Integer getCountyId() {
		return this.countyId;
	}

	public void setCountyId(Integer countyId) {
		this.countyId = countyId;
	}

	public String getFullDesc() {
		return this.fullDesc;
	}

	public void setFullDesc(String fullDesc) {
		this.fullDesc = fullDesc;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebAddr() {
		return this.webAddr;
	}

	public void setWebAddr(String webAddr) {
		this.webAddr = webAddr;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

}
