package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

/**
 * Facilities generated by hbm2java
 */
public class Facilities implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int facilityId;
	private ReferenceData referenceData;
	private Contacts contacts;
	private String facilityDescription;
	private Integer roomCapacity;
	private Integer roomSize;
	private Boolean roomConnectivity;
	private Boolean equipmentAvailable;
	private String roomEquipmentNotes;
	private Integer connectivityType;
	private String wirelessAccessInfomation;
	private Boolean isActive;
	private Integer premiseId;
	private String facilityTypeName;

	public Facilities() {
	}

	public Facilities(int facilityId, Contacts contacts) {
		this.facilityId = facilityId;
		this.contacts = contacts;
	}

	public int getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(int facilityId) {
		this.facilityId = facilityId;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public Facilities(int facilityId, ReferenceData referenceData,
			Contacts contacts, String facilityDescription,
			Integer roomCapacity, Integer roomSize, Boolean roomConnectivity,
			Boolean equipmentAvailable, String roomEquipmentNotes,
			Integer connectivityType, String wirelessAccessInfomation,
			Boolean isActive, Integer premiseId, String facilityTypeName) {
		super();
		this.facilityId = facilityId;
		this.referenceData = referenceData;
		this.contacts = contacts;
		this.facilityDescription = facilityDescription;
		this.roomCapacity = roomCapacity;
		this.roomSize = roomSize;
		this.roomConnectivity = roomConnectivity;
		this.equipmentAvailable = equipmentAvailable;
		this.roomEquipmentNotes = roomEquipmentNotes;
		this.connectivityType = connectivityType;
		this.wirelessAccessInfomation = wirelessAccessInfomation;
		this.isActive = isActive;
		this.premiseId = premiseId;
		this.facilityTypeName = facilityTypeName;
	}

	public ReferenceData getReferenceData() {
		return referenceData;
	}

	public void setReferenceData(ReferenceData referenceData) {
		this.referenceData = referenceData;
	}

	public String getFacilityDescription() {
		return this.facilityDescription;
	}

	public void setFacilityDescription(String facilityDescription) {
		this.facilityDescription = facilityDescription;
	}

	public Integer getRoomCapacity() {
		return this.roomCapacity;
	}

	public void setRoomCapacity(Integer roomCapacity) {
		this.roomCapacity = roomCapacity;
	}

	public Integer getRoomSize() {
		return this.roomSize;
	}

	public void setRoomSize(Integer roomSize) {
		this.roomSize = roomSize;
	}

	public Boolean getRoomConnectivity() {
		return this.roomConnectivity;
	}

	public void setRoomConnectivity(Boolean roomConnectivity) {
		this.roomConnectivity = roomConnectivity;
	}

	public Boolean getEquipmentAvailable() {
		return this.equipmentAvailable;
	}

	public void setEquipmentAvailable(Boolean equipmentAvailable) {
		this.equipmentAvailable = equipmentAvailable;
	}

	public String getRoomEquipmentNotes() {
		return this.roomEquipmentNotes;
	}

	public void setRoomEquipmentNotes(String roomEquipmentNotes) {
		this.roomEquipmentNotes = roomEquipmentNotes;
	}

	public Integer getConnectivityType() {
		return this.connectivityType;
	}

	public void setConnectivityType(Integer connectivityType) {
		this.connectivityType = connectivityType;
	}

	public String getWirelessAccessInfomation() {
		return this.wirelessAccessInfomation;
	}

	public void setWirelessAccessInfomation(String wirelessAccessInfomation) {
		this.wirelessAccessInfomation = wirelessAccessInfomation;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Integer getPremiseId() {
		return this.premiseId;
	}

	public void setPremiseId(Integer premiseId) {
		this.premiseId = premiseId;
	}

	public String getFacilityTypeName() {
		return this.facilityTypeName;
	}

	public void setFacilityTypeName(String facilityTypeName) {
		this.facilityTypeName = facilityTypeName;
	}

}
