package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

/**
 * GovtOfficeRegions generated by hbm2java
 */
public class GovtOfficeRegions implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int govtOfficeRegionId;
	private Counties counties;
	private String name;
	private String description;
	private Boolean isActive;

	public GovtOfficeRegions() {
	}

	public GovtOfficeRegions(int govtOfficeRegionId) {
		this.govtOfficeRegionId = govtOfficeRegionId;
	}

	public GovtOfficeRegions(int govtOfficeRegionId, Counties counties,
			String name, String description, Boolean isActive) {
		this.govtOfficeRegionId = govtOfficeRegionId;
		this.counties = counties;
		this.name = name;
		this.description = description;
		this.isActive = isActive;
	}

	public int getGovtOfficeRegionId() {
		return this.govtOfficeRegionId;
	}

	public void setGovtOfficeRegionId(int govtOfficeRegionId) {
		this.govtOfficeRegionId = govtOfficeRegionId;
	}

	public Counties getCounties() {
		return this.counties;
	}

	public void setCounties(Counties counties) {
		this.counties = counties;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
