package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Organisations generated by hbm2java
 */
public class Organisations implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int organisationId;
	private Contacts contacts;
	private TrustDistricts trustDistricts;
	private ReferenceData referenceData;
	private String name;
	private String shortDesc;
	private String addr1;
	private String addr2;
	private String addr3;
	private String city;
	private String county;
	private Boolean preferredOrg;
	private Boolean expOfInterest;
	private String fullDesc;
	private String phoneNumber;
	private String fax;
	private String email;
	private String webAddr;
	private String charityNumber;
	private String companyNumber;
	private String orgSpecicalism;
	private String serviceDisCap;
	private String serviceBarCap;
	private String serviceBenCap;
	private String servicePerCirCap;
	private String serviceEthCap;

	public Organisations() {
		super();
	}

	public Organisations(int organisationId) {
		super();
		this.organisationId = organisationId;
	}

	public Organisations(int organisationId, Contacts contacts,
			TrustDistricts trustDistricts, ReferenceData referenceData,
			String name, String shortDesc, String addr1, String addr2,
			String addr3, String city, String county, Boolean preferredOrg,
			Boolean expOfInterest, String fullDesc, String phoneNumber,
			String fax, String email, String webAddr, String charityNumber,
			String companyNumber, String orgSpecicalism, String serviceDisCap,
			String serviceBarCap, String serviceBenCap,
			String servicePerCirCap, String serviceEthCap,
			String accreditation, String eoiprogramme, String eoiservice,
			Integer govOffRegionId, String postCode, Boolean isActive,
			Set<OrganisationService> organisationServices,
			Set<OrganisationProgramme> organisationProgrammes,
			Set<SupportingMaterials> supportingMaterialses) {
		super();
		this.organisationId = organisationId;
		this.contacts = contacts;
		this.trustDistricts = trustDistricts;
		this.referenceData = referenceData;
		this.name = name;
		this.shortDesc = shortDesc;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.city = city;
		this.county = county;
		this.preferredOrg = preferredOrg;
		this.expOfInterest = expOfInterest;
		this.fullDesc = fullDesc;
		this.phoneNumber = phoneNumber;
		this.fax = fax;
		this.email = email;
		this.webAddr = webAddr;
		this.charityNumber = charityNumber;
		this.companyNumber = companyNumber;
		this.orgSpecicalism = orgSpecicalism;
		this.serviceDisCap = serviceDisCap;
		this.serviceBarCap = serviceBarCap;
		this.serviceBenCap = serviceBenCap;
		this.servicePerCirCap = servicePerCirCap;
		this.serviceEthCap = serviceEthCap;
		this.accreditation = accreditation;
		this.eoiprogramme = eoiprogramme;
		this.eoiservice = eoiservice;
		this.govOffRegionId = govOffRegionId;
		this.postCode = postCode;
		this.isActive = isActive;
		this.organisationServices = organisationServices;
		this.organisationProgrammes = organisationProgrammes;
		this.supportingMaterialses = supportingMaterialses;
	}

	public int getOrganisationId() {
		return organisationId;
	}

	public void setOrganisationId(int organisationId) {
		this.organisationId = organisationId;
	}

	public Contacts getContacts() {
		return contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public TrustDistricts getTrustDistricts() {
		return trustDistricts;
	}

	public void setTrustDistricts(TrustDistricts trustDistricts) {
		this.trustDistricts = trustDistricts;
	}

	public ReferenceData getReferenceData() {
		return referenceData;
	}

	public void setReferenceData(ReferenceData referenceData) {
		this.referenceData = referenceData;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDesc() {
		return shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getAddr1() {
		return addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getAddr3() {
		return addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public Boolean getPreferredOrg() {
		return preferredOrg;
	}

	public void setPreferredOrg(Boolean preferredOrg) {
		this.preferredOrg = preferredOrg;
	}

	public Boolean getExpOfInterest() {
		return expOfInterest;
	}

	public void setExpOfInterest(Boolean expOfInterest) {
		this.expOfInterest = expOfInterest;
	}

	public String getFullDesc() {
		return fullDesc;
	}

	public void setFullDesc(String fullDesc) {
		this.fullDesc = fullDesc;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebAddr() {
		return webAddr;
	}

	public void setWebAddr(String webAddr) {
		this.webAddr = webAddr;
	}

	public String getCharityNumber() {
		return charityNumber;
	}

	public void setCharityNumber(String charityNumber) {
		this.charityNumber = charityNumber;
	}

	public String getCompanyNumber() {
		return companyNumber;
	}

	public void setCompanyNumber(String companyNumber) {
		this.companyNumber = companyNumber;
	}

	public String getOrgSpecicalism() {
		return orgSpecicalism;
	}

	public void setOrgSpecicalism(String orgSpecicalism) {
		this.orgSpecicalism = orgSpecicalism;
	}

	public String getServiceDisCap() {
		return serviceDisCap;
	}

	public void setServiceDisCap(String serviceDisCap) {
		this.serviceDisCap = serviceDisCap;
	}

	public String getServiceBarCap() {
		return serviceBarCap;
	}

	public void setServiceBarCap(String serviceBarCap) {
		this.serviceBarCap = serviceBarCap;
	}

	public String getServiceBenCap() {
		return serviceBenCap;
	}

	public void setServiceBenCap(String serviceBenCap) {
		this.serviceBenCap = serviceBenCap;
	}

	public String getServicePerCirCap() {
		return servicePerCirCap;
	}

	public void setServicePerCirCap(String servicePerCirCap) {
		this.servicePerCirCap = servicePerCirCap;
	}

	public String getServiceEthCap() {
		return serviceEthCap;
	}

	public void setServiceEthCap(String serviceEthCap) {
		this.serviceEthCap = serviceEthCap;
	}

	public String getAccreditation() {
		return accreditation;
	}

	public void setAccreditation(String accreditation) {
		this.accreditation = accreditation;
	}

	public String getEoiprogramme() {
		return eoiprogramme;
	}

	public void setEoiprogramme(String eoiprogramme) {
		this.eoiprogramme = eoiprogramme;
	}

	public String getEoiservice() {
		return eoiservice;
	}

	public void setEoiservice(String eoiservice) {
		this.eoiservice = eoiservice;
	}

	public Integer getGovOffRegionId() {
		return govOffRegionId;
	}

	public void setGovOffRegionId(Integer govOffRegionId) {
		this.govOffRegionId = govOffRegionId;
	}

	public String getPostCode() {
		return postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<OrganisationService> getOrganisationServices() {
		return organisationServices;
	}

	public void setOrganisationServices(
			Set<OrganisationService> organisationServices) {
		this.organisationServices = organisationServices;
	}

	public Set<OrganisationProgramme> getOrganisationProgrammes() {
		return organisationProgrammes;
	}

	public void setOrganisationProgrammes(
			Set<OrganisationProgramme> organisationProgrammes) {
		this.organisationProgrammes = organisationProgrammes;
	}

	public Set<SupportingMaterials> getSupportingMaterialses() {
		return supportingMaterialses;
	}

	public void setSupportingMaterialses(
			Set<SupportingMaterials> supportingMaterialses) {
		this.supportingMaterialses = supportingMaterialses;
	}

	private String accreditation;
	private String eoiprogramme;
	private String eoiservice;
	private Integer govOffRegionId;
	private String postCode;
	private Boolean isActive;
	private Set<OrganisationService> organisationServices = new HashSet<OrganisationService>(
			0);
	private Set<OrganisationProgramme> organisationProgrammes = new HashSet<OrganisationProgramme>(
			0);
	private Set<SupportingMaterials> supportingMaterialses = new HashSet<SupportingMaterials>(
			0);

}
