package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA



/**
 * OrganisationService generated by hbm2java
 */
public class OrganisationService  implements java.io.Serializable {


     private int id;
     private Services services;
     private Organisations organisations;
     private String role;

    public OrganisationService() {
    }

	
    public OrganisationService(int id, Services services, Organisations organisations) {
        this.id = id;
        this.services = services;
        this.organisations = organisations;
    }
    public OrganisationService(int id, Services services, Organisations organisations, String role) {
       this.id = id;
       this.services = services;
       this.organisations = organisations;
       this.role = role;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Services getServices() {
        return this.services;
    }
    
    public void setServices(Services services) {
        this.services = services;
    }
    public Organisations getOrganisations() {
        return this.organisations;
    }
    
    public void setOrganisations(Organisations organisations) {
        this.organisations = organisations;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


