package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Organisation generated by hbm2java
 */
@Entity
public class Organisation implements java.io.Serializable {
	@Id
	private int organisationId;
	private Contact contact;
	private TypeOfBusiness typeOfBusiness;
	private TrustDistrict trustDistrict;
	private GovOfficeRegion govOfficeRegion;
	private County county;
	private String name;
	private String shortDesc;
	private String addr1;
	private String addr2;
	private String addr3;
	private String city;
	private Boolean preferredOrg;
	private Boolean expOfInterest;
	private String fullDesc;
	private String phoneNumber;
	private String fax;
	private String email;
	private String webAddr;
	private String charityNumber;
	private String companyNumber;
	private String orgSpecicalism;
	private String serviceDisCap;
	private String serviceBarCap;
	private String serviceBenCap;
	private String servicePerCirCap;
	private String serviceEthCap;
	private String accreditation;
	private String eoiprogramme;
	private String eoiservice;
	private String postCode;
	private Boolean status;
	private String role;
	private Set<Premise> premises = new HashSet<Premise>(0);
	private Set<SupportingMaterial> supportingMaterials = new HashSet<SupportingMaterial>(
			0);
	private Set<Directorate> directorates = new HashSet<Directorate>(0);

	public Organisation() {
	}

	public Organisation(int organisationId) {
		this.organisationId = organisationId;
	}

	public Organisation(int organisationId, Contact contact,
			TypeOfBusiness typeOfBusiness, TrustDistrict trustDistrict,
			GovOfficeRegion govOfficeRegion, County county, String name,
			String shortDesc, String addr1, String addr2, String addr3,
			String city, Boolean preferredOrg, Boolean expOfInterest,
			String fullDesc, String phoneNumber, String fax, String email,
			String webAddr, String charityNumber, String companyNumber,
			String orgSpecicalism, String serviceDisCap, String serviceBarCap,
			String serviceBenCap, String servicePerCirCap,
			String serviceEthCap, String accreditation, String eoiprogramme,
			String eoiservice, String postCode, Boolean status, String role,
			Set<Premise> premises, Set<SupportingMaterial> supportingMaterials,
			Set<Directorate> directorates) {
		this.organisationId = organisationId;
		this.contact = contact;
		this.typeOfBusiness = typeOfBusiness;
		this.trustDistrict = trustDistrict;
		this.govOfficeRegion = govOfficeRegion;
		this.county = county;
		this.name = name;
		this.shortDesc = shortDesc;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.city = city;
		this.preferredOrg = preferredOrg;
		this.expOfInterest = expOfInterest;
		this.fullDesc = fullDesc;
		this.phoneNumber = phoneNumber;
		this.fax = fax;
		this.email = email;
		this.webAddr = webAddr;
		this.charityNumber = charityNumber;
		this.companyNumber = companyNumber;
		this.orgSpecicalism = orgSpecicalism;
		this.serviceDisCap = serviceDisCap;
		this.serviceBarCap = serviceBarCap;
		this.serviceBenCap = serviceBenCap;
		this.servicePerCirCap = servicePerCirCap;
		this.serviceEthCap = serviceEthCap;
		this.accreditation = accreditation;
		this.eoiprogramme = eoiprogramme;
		this.eoiservice = eoiservice;
		this.postCode = postCode;
		this.status = status;
		this.role = role;
		this.premises = premises;
		this.supportingMaterials = supportingMaterials;
		this.directorates = directorates;
	}

	public int getOrganisationId() {
		return this.organisationId;
	}

	public void setOrganisationId(int organisationId) {
		this.organisationId = organisationId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public TypeOfBusiness getTypeOfBusiness() {
		return this.typeOfBusiness;
	}

	public void setTypeOfBusiness(TypeOfBusiness typeOfBusiness) {
		this.typeOfBusiness = typeOfBusiness;
	}

	public TrustDistrict getTrustDistrict() {
		return this.trustDistrict;
	}

	public void setTrustDistrict(TrustDistrict trustDistrict) {
		this.trustDistrict = trustDistrict;
	}

	public GovOfficeRegion getGovOfficeRegion() {
		return this.govOfficeRegion;
	}

	public void setGovOfficeRegion(GovOfficeRegion govOfficeRegion) {
		this.govOfficeRegion = govOfficeRegion;
	}

	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Boolean getPreferredOrg() {
		return this.preferredOrg;
	}

	public void setPreferredOrg(Boolean preferredOrg) {
		this.preferredOrg = preferredOrg;
	}

	public Boolean getExpOfInterest() {
		return this.expOfInterest;
	}

	public void setExpOfInterest(Boolean expOfInterest) {
		this.expOfInterest = expOfInterest;
	}

	public String getFullDesc() {
		return this.fullDesc;
	}

	public void setFullDesc(String fullDesc) {
		this.fullDesc = fullDesc;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebAddr() {
		return this.webAddr;
	}

	public void setWebAddr(String webAddr) {
		this.webAddr = webAddr;
	}

	public String getCharityNumber() {
		return this.charityNumber;
	}

	public void setCharityNumber(String charityNumber) {
		this.charityNumber = charityNumber;
	}

	public String getCompanyNumber() {
		return this.companyNumber;
	}

	public void setCompanyNumber(String companyNumber) {
		this.companyNumber = companyNumber;
	}

	public String getOrgSpecicalism() {
		return this.orgSpecicalism;
	}

	public void setOrgSpecicalism(String orgSpecicalism) {
		this.orgSpecicalism = orgSpecicalism;
	}

	public String getServiceDisCap() {
		return this.serviceDisCap;
	}

	public void setServiceDisCap(String serviceDisCap) {
		this.serviceDisCap = serviceDisCap;
	}

	public String getServiceBarCap() {
		return this.serviceBarCap;
	}

	public void setServiceBarCap(String serviceBarCap) {
		this.serviceBarCap = serviceBarCap;
	}

	public String getServiceBenCap() {
		return this.serviceBenCap;
	}

	public void setServiceBenCap(String serviceBenCap) {
		this.serviceBenCap = serviceBenCap;
	}

	public String getServicePerCirCap() {
		return this.servicePerCirCap;
	}

	public void setServicePerCirCap(String servicePerCirCap) {
		this.servicePerCirCap = servicePerCirCap;
	}

	public String getServiceEthCap() {
		return this.serviceEthCap;
	}

	public void setServiceEthCap(String serviceEthCap) {
		this.serviceEthCap = serviceEthCap;
	}

	public String getAccreditation() {
		return this.accreditation;
	}

	public void setAccreditation(String accreditation) {
		this.accreditation = accreditation;
	}

	public String getEoiprogramme() {
		return this.eoiprogramme;
	}

	public void setEoiprogramme(String eoiprogramme) {
		this.eoiprogramme = eoiprogramme;
	}

	public String getEoiservice() {
		return this.eoiservice;
	}

	public void setEoiservice(String eoiservice) {
		this.eoiservice = eoiservice;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<Premise> getPremises() {
		return this.premises;
	}

	public void setPremises(Set<Premise> premises) {
		this.premises = premises;
	}

	public Set<SupportingMaterial> getSupportingMaterials() {
		return this.supportingMaterials;
	}

	public void setSupportingMaterials(
			Set<SupportingMaterial> supportingMaterials) {
		this.supportingMaterials = supportingMaterials;
	}

	public Set<Directorate> getDirectorates() {
		return this.directorates;
	}

	public void setDirectorates(Set<Directorate> directorates) {
		this.directorates = directorates;
	}

}
