package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

/**
 * OrganisationService generated by hbm2java
 */
public class OrganisationService implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Services services;
	private Organisations organisations;
	private String role;

	public OrganisationService() {
	}

	public OrganisationService(int id) {
		this.id = id;
	}

	public OrganisationService(int id, Services services,
			Organisations organisations, String role) {
		this.id = id;
		this.services = services;
		this.organisations = organisations;
		this.role = role;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public Organisations getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Organisations organisations) {
		this.organisations = organisations;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
