package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Premises generated by hbm2java
 */
public class Premises implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int premiseId;
	private ReferenceData referenceData;
	private String name;
	private String locationName;
	private String knownAs;
	private Boolean primaryLocation;
	private Boolean locationManaged;
	private Integer orgnisationId;
	private String locationStatus;
	private Boolean stnetworkConectivity;
	private Date locationStatusDate;
	private String locationType;
	private String locationDescription;
	private String addressLine1;
	private String addressLine2;
	private String phoneNumber;
	private String postcode;
	private String faxNumber;
	private String cityTown;
	private String county;
	private Boolean isNewShop;
	private String nation;
	private Date shopFlagDate;
	private Boolean specialistShop;
	private String accreditations;
	private String jcpoffices;
	private String localDemographicIssue;
	private Integer isnetwork;
	private Boolean roomAvailability;
	private Boolean volunteeringOpportunities;
	private String outreachLocation;
	private String localHotel;
	private String travelDetails;
	private Boolean visitorParkingOnsite;
	private String travelNearestBus;
	private Boolean hostVisits;
	private Integer contactId;
	private Double roomOnlyRate;
	private Double negotiatedRoomOnlyRate;
	private Double bbrate;
	private Double bbnegotiatedRate;
	private Boolean lunch;
	private Date lastNegotiatedDate;
	private Date reNegotiatedOn;
	private Integer noOfMeetingRoom;
	private Double meetingRoomRatePerDay;
	private Boolean isActive;
	private Set<ServicePremise> servicePremises = new HashSet<ServicePremise>(0);

	public Premises() {
	}

	public Premises(int premiseId) {
		this.premiseId = premiseId;
	}

	public Premises(int premiseId, ReferenceData referenceData, String name,
			String locationName, String knownAs, Boolean primaryLocation,
			Boolean locationManaged, Integer orgnisationId,
			String locationStatus, Boolean stnetworkConectivity,
			Date locationStatusDate, String locationType,
			String locationDescription, String addressLine1,
			String addressLine2, String phoneNumber, String postcode,
			String faxNumber, String cityTown, String county,
			Boolean isNewShop, String nation, Date shopFlagDate,
			Boolean specialistShop, String accreditations, String jcpoffices,
			String localDemographicIssue, Integer isnetwork,
			Boolean roomAvailability, Boolean volunteeringOpportunities,
			String outreachLocation, String localHotel, String travelDetails,
			Boolean visitorParkingOnsite, String travelNearestBus,
			Boolean hostVisits, Integer contactId, Double roomOnlyRate,
			Double negotiatedRoomOnlyRate, Double bbrate,
			Double bbnegotiatedRate, Boolean lunch, Date lastNegotiatedDate,
			Date reNegotiatedOn, Integer noOfMeetingRoom,
			Double meetingRoomRatePerDay, Boolean isActive,
			Set<ServicePremise> servicePremises) {
		super();
		this.premiseId = premiseId;
		this.referenceData = referenceData;
		this.name = name;
		this.locationName = locationName;
		this.knownAs = knownAs;
		this.primaryLocation = primaryLocation;
		this.locationManaged = locationManaged;
		this.orgnisationId = orgnisationId;
		this.locationStatus = locationStatus;
		this.stnetworkConectivity = stnetworkConectivity;
		this.locationStatusDate = locationStatusDate;
		this.locationType = locationType;
		this.locationDescription = locationDescription;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.phoneNumber = phoneNumber;
		this.postcode = postcode;
		this.faxNumber = faxNumber;
		this.cityTown = cityTown;
		this.county = county;
		this.isNewShop = isNewShop;
		this.nation = nation;
		this.shopFlagDate = shopFlagDate;
		this.specialistShop = specialistShop;
		this.accreditations = accreditations;
		this.jcpoffices = jcpoffices;
		this.localDemographicIssue = localDemographicIssue;
		this.isnetwork = isnetwork;
		this.roomAvailability = roomAvailability;
		this.volunteeringOpportunities = volunteeringOpportunities;
		this.outreachLocation = outreachLocation;
		this.localHotel = localHotel;
		this.travelDetails = travelDetails;
		this.visitorParkingOnsite = visitorParkingOnsite;
		this.travelNearestBus = travelNearestBus;
		this.hostVisits = hostVisits;
		this.contactId = contactId;
		this.roomOnlyRate = roomOnlyRate;
		this.negotiatedRoomOnlyRate = negotiatedRoomOnlyRate;
		this.bbrate = bbrate;
		this.bbnegotiatedRate = bbnegotiatedRate;
		this.lunch = lunch;
		this.lastNegotiatedDate = lastNegotiatedDate;
		this.reNegotiatedOn = reNegotiatedOn;
		this.noOfMeetingRoom = noOfMeetingRoom;
		this.meetingRoomRatePerDay = meetingRoomRatePerDay;
		this.isActive = isActive;
		this.servicePremises = servicePremises;
	}

	public int getPremiseId() {
		return premiseId;
	}

	public void setPremiseId(int premiseId) {
		this.premiseId = premiseId;
	}

	public ReferenceData getReferenceData() {
		return referenceData;
	}

	public void setReferenceData(ReferenceData referenceData) {
		this.referenceData = referenceData;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getKnownAs() {
		return knownAs;
	}

	public void setKnownAs(String knownAs) {
		this.knownAs = knownAs;
	}

	public Boolean getPrimaryLocation() {
		return primaryLocation;
	}

	public void setPrimaryLocation(Boolean primaryLocation) {
		this.primaryLocation = primaryLocation;
	}

	public Boolean getLocationManaged() {
		return locationManaged;
	}

	public void setLocationManaged(Boolean locationManaged) {
		this.locationManaged = locationManaged;
	}

	public Integer getOrgnisationId() {
		return orgnisationId;
	}

	public void setOrgnisationId(Integer orgnisationId) {
		this.orgnisationId = orgnisationId;
	}

	public String getLocationStatus() {
		return locationStatus;
	}

	public void setLocationStatus(String locationStatus) {
		this.locationStatus = locationStatus;
	}

	public Boolean getStnetworkConectivity() {
		return stnetworkConectivity;
	}

	public void setStnetworkConectivity(Boolean stnetworkConectivity) {
		this.stnetworkConectivity = stnetworkConectivity;
	}

	public Date getLocationStatusDate() {
		return locationStatusDate;
	}

	public void setLocationStatusDate(Date locationStatusDate) {
		this.locationStatusDate = locationStatusDate;
	}

	public String getLocationType() {
		return locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	public String getLocationDescription() {
		return locationDescription;
	}

	public void setLocationDescription(String locationDescription) {
		this.locationDescription = locationDescription;
	}

	public String getAddressLine1() {
		return addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getFaxNumber() {
		return faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getCityTown() {
		return cityTown;
	}

	public void setCityTown(String cityTown) {
		this.cityTown = cityTown;
	}

	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public Boolean getIsNewShop() {
		return isNewShop;
	}

	public void setIsNewShop(Boolean isNewShop) {
		this.isNewShop = isNewShop;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public Date getShopFlagDate() {
		return shopFlagDate;
	}

	public void setShopFlagDate(Date shopFlagDate) {
		this.shopFlagDate = shopFlagDate;
	}

	public Boolean getSpecialistShop() {
		return specialistShop;
	}

	public void setSpecialistShop(Boolean specialistShop) {
		this.specialistShop = specialistShop;
	}

	public String getAccreditations() {
		return accreditations;
	}

	public void setAccreditations(String accreditations) {
		this.accreditations = accreditations;
	}

	public String getJcpoffices() {
		return jcpoffices;
	}

	public void setJcpoffices(String jcpoffices) {
		this.jcpoffices = jcpoffices;
	}

	public String getLocalDemographicIssue() {
		return localDemographicIssue;
	}

	public void setLocalDemographicIssue(String localDemographicIssue) {
		this.localDemographicIssue = localDemographicIssue;
	}

	public Integer getIsnetwork() {
		return isnetwork;
	}

	public void setIsnetwork(Integer isnetwork) {
		this.isnetwork = isnetwork;
	}

	public Boolean getRoomAvailability() {
		return roomAvailability;
	}

	public void setRoomAvailability(Boolean roomAvailability) {
		this.roomAvailability = roomAvailability;
	}

	public Boolean getVolunteeringOpportunities() {
		return volunteeringOpportunities;
	}

	public void setVolunteeringOpportunities(Boolean volunteeringOpportunities) {
		this.volunteeringOpportunities = volunteeringOpportunities;
	}

	public String getOutreachLocation() {
		return outreachLocation;
	}

	public void setOutreachLocation(String outreachLocation) {
		this.outreachLocation = outreachLocation;
	}

	public String getLocalHotel() {
		return localHotel;
	}

	public void setLocalHotel(String localHotel) {
		this.localHotel = localHotel;
	}

	public String getTravelDetails() {
		return travelDetails;
	}

	public void setTravelDetails(String travelDetails) {
		this.travelDetails = travelDetails;
	}

	public Boolean getVisitorParkingOnsite() {
		return visitorParkingOnsite;
	}

	public void setVisitorParkingOnsite(Boolean visitorParkingOnsite) {
		this.visitorParkingOnsite = visitorParkingOnsite;
	}

	public String getTravelNearestBus() {
		return travelNearestBus;
	}

	public void setTravelNearestBus(String travelNearestBus) {
		this.travelNearestBus = travelNearestBus;
	}

	public Boolean getHostVisits() {
		return hostVisits;
	}

	public void setHostVisits(Boolean hostVisits) {
		this.hostVisits = hostVisits;
	}

	public Integer getContactId() {
		return contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Double getRoomOnlyRate() {
		return roomOnlyRate;
	}

	public void setRoomOnlyRate(Double roomOnlyRate) {
		this.roomOnlyRate = roomOnlyRate;
	}

	public Double getNegotiatedRoomOnlyRate() {
		return negotiatedRoomOnlyRate;
	}

	public void setNegotiatedRoomOnlyRate(Double negotiatedRoomOnlyRate) {
		this.negotiatedRoomOnlyRate = negotiatedRoomOnlyRate;
	}

	public Double getBbrate() {
		return bbrate;
	}

	public void setBbrate(Double bbrate) {
		this.bbrate = bbrate;
	}

	public Double getBbnegotiatedRate() {
		return bbnegotiatedRate;
	}

	public void setBbnegotiatedRate(Double bbnegotiatedRate) {
		this.bbnegotiatedRate = bbnegotiatedRate;
	}

	public Boolean getLunch() {
		return lunch;
	}

	public void setLunch(Boolean lunch) {
		this.lunch = lunch;
	}

	public Date getLastNegotiatedDate() {
		return lastNegotiatedDate;
	}

	public void setLastNegotiatedDate(Date lastNegotiatedDate) {
		this.lastNegotiatedDate = lastNegotiatedDate;
	}

	public Date getReNegotiatedOn() {
		return reNegotiatedOn;
	}

	public void setReNegotiatedOn(Date reNegotiatedOn) {
		this.reNegotiatedOn = reNegotiatedOn;
	}

	public Integer getNoOfMeetingRoom() {
		return noOfMeetingRoom;
	}

	public void setNoOfMeetingRoom(Integer noOfMeetingRoom) {
		this.noOfMeetingRoom = noOfMeetingRoom;
	}

	public Double getMeetingRoomRatePerDay() {
		return meetingRoomRatePerDay;
	}

	public void setMeetingRoomRatePerDay(Double meetingRoomRatePerDay) {
		this.meetingRoomRatePerDay = meetingRoomRatePerDay;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<ServicePremise> getServicePremises() {
		return servicePremises;
	}

	public void setServicePremises(Set<ServicePremise> servicePremises) {
		this.servicePremises = servicePremises;
	}

}
