package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Premise generated by hbm2java
 */
public class Premise implements java.io.Serializable {

	private int premiseId;
	private Country country;
	private Organisation organisation;
	private ReferenceData referenceData;
	private String name;
	private String locationName;
	private String knownAs;
	private Boolean primaryLocation;
	private Boolean locationManaged;
	private String locationStatus;
	private Boolean stnetworkConectivity;
	private Date locationStatusDate;
	private String locationType;
	private String locationDescription;
	private String addressLine1;
	private String addressLine2;
	private String phoneNumber;
	private String postcode;
	private String faxNumber;
	private String cityTown;
	private String county;
	private Boolean isNewShop;
	private Date shopFlagDate;
	private Boolean specialistShop;
	private String accreditations;
	private String jcpoffices;
	private String localDemographicIssue;
	private Integer isnetwork;
	private Boolean roomAvailability;
	private Boolean volunteeringOpportunities;
	private String outreachLocation;
	private String localHotel;
	private String travelDetails;
	private Boolean visitorParkingOnsite;
	private String travelNearestBus;
	private Boolean hostVisits;
	private Integer contactId;
	private Double roomOnlyRate;
	private Double negotiatedRoomOnlyRate;
	private Double bbrate;
	private Double bbnegotiatedRate;
	private Boolean lunch;
	private Date lastNegotiatedDate;
	private Date reNegotiatedOn;
	private Integer noOfMeetingRoom;
	private Double meetingRoomRatePerDay;
	private Boolean status;

	public Premise() {
	}

	public Premise(int premiseId) {
		this.premiseId = premiseId;
	}

	public Premise(int premiseId, Country country, Organisation organisation,
			ReferenceData referenceData, String name, String locationName,
			String knownAs, Boolean primaryLocation, Boolean locationManaged,
			String locationStatus, Boolean stnetworkConectivity,
			Date locationStatusDate, String locationType,
			String locationDescription, String addressLine1,
			String addressLine2, String phoneNumber, String postcode,
			String faxNumber, String cityTown, String county,
			Boolean isNewShop, Date shopFlagDate, Boolean specialistShop,
			String accreditations, String jcpoffices,
			String localDemographicIssue, Integer isnetwork,
			Boolean roomAvailability, Boolean volunteeringOpportunities,
			String outreachLocation, String localHotel, String travelDetails,
			Boolean visitorParkingOnsite, String travelNearestBus,
			Boolean hostVisits, Integer contactId, Double roomOnlyRate,
			Double negotiatedRoomOnlyRate, Double bbrate,
			Double bbnegotiatedRate, Boolean lunch, Date lastNegotiatedDate,
			Date reNegotiatedOn, Integer noOfMeetingRoom,
			Double meetingRoomRatePerDay, Boolean status) {
		this.premiseId = premiseId;
		this.country = country;
		this.organisation = organisation;
		this.referenceData = referenceData;
		this.name = name;
		this.locationName = locationName;
		this.knownAs = knownAs;
		this.primaryLocation = primaryLocation;
		this.locationManaged = locationManaged;
		this.locationStatus = locationStatus;
		this.stnetworkConectivity = stnetworkConectivity;
		this.locationStatusDate = locationStatusDate;
		this.locationType = locationType;
		this.locationDescription = locationDescription;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.phoneNumber = phoneNumber;
		this.postcode = postcode;
		this.faxNumber = faxNumber;
		this.cityTown = cityTown;
		this.county = county;
		this.isNewShop = isNewShop;
		this.shopFlagDate = shopFlagDate;
		this.specialistShop = specialistShop;
		this.accreditations = accreditations;
		this.jcpoffices = jcpoffices;
		this.localDemographicIssue = localDemographicIssue;
		this.isnetwork = isnetwork;
		this.roomAvailability = roomAvailability;
		this.volunteeringOpportunities = volunteeringOpportunities;
		this.outreachLocation = outreachLocation;
		this.localHotel = localHotel;
		this.travelDetails = travelDetails;
		this.visitorParkingOnsite = visitorParkingOnsite;
		this.travelNearestBus = travelNearestBus;
		this.hostVisits = hostVisits;
		this.contactId = contactId;
		this.roomOnlyRate = roomOnlyRate;
		this.negotiatedRoomOnlyRate = negotiatedRoomOnlyRate;
		this.bbrate = bbrate;
		this.bbnegotiatedRate = bbnegotiatedRate;
		this.lunch = lunch;
		this.lastNegotiatedDate = lastNegotiatedDate;
		this.reNegotiatedOn = reNegotiatedOn;
		this.noOfMeetingRoom = noOfMeetingRoom;
		this.meetingRoomRatePerDay = meetingRoomRatePerDay;
		this.status = status;
	}

	public int getPremiseId() {
		return this.premiseId;
	}

	public void setPremiseId(int premiseId) {
		this.premiseId = premiseId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	public ReferenceData getReferenceData() {
		return this.referenceData;
	}

	public void setReferenceData(ReferenceData referenceData) {
		this.referenceData = referenceData;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getKnownAs() {
		return this.knownAs;
	}

	public void setKnownAs(String knownAs) {
		this.knownAs = knownAs;
	}

	public Boolean getPrimaryLocation() {
		return this.primaryLocation;
	}

	public void setPrimaryLocation(Boolean primaryLocation) {
		this.primaryLocation = primaryLocation;
	}

	public Boolean getLocationManaged() {
		return this.locationManaged;
	}

	public void setLocationManaged(Boolean locationManaged) {
		this.locationManaged = locationManaged;
	}

	public String getLocationStatus() {
		return this.locationStatus;
	}

	public void setLocationStatus(String locationStatus) {
		this.locationStatus = locationStatus;
	}

	public Boolean getStnetworkConectivity() {
		return this.stnetworkConectivity;
	}

	public void setStnetworkConectivity(Boolean stnetworkConectivity) {
		this.stnetworkConectivity = stnetworkConectivity;
	}

	public Date getLocationStatusDate() {
		return this.locationStatusDate;
	}

	public void setLocationStatusDate(Date locationStatusDate) {
		this.locationStatusDate = locationStatusDate;
	}

	public String getLocationType() {
		return this.locationType;
	}

	public void setLocationType(String locationType) {
		this.locationType = locationType;
	}

	public String getLocationDescription() {
		return this.locationDescription;
	}

	public void setLocationDescription(String locationDescription) {
		this.locationDescription = locationDescription;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getCityTown() {
		return this.cityTown;
	}

	public void setCityTown(String cityTown) {
		this.cityTown = cityTown;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public Boolean getIsNewShop() {
		return this.isNewShop;
	}

	public void setIsNewShop(Boolean isNewShop) {
		this.isNewShop = isNewShop;
	}

	public Date getShopFlagDate() {
		return this.shopFlagDate;
	}

	public void setShopFlagDate(Date shopFlagDate) {
		this.shopFlagDate = shopFlagDate;
	}

	public Boolean getSpecialistShop() {
		return this.specialistShop;
	}

	public void setSpecialistShop(Boolean specialistShop) {
		this.specialistShop = specialistShop;
	}

	public String getAccreditations() {
		return this.accreditations;
	}

	public void setAccreditations(String accreditations) {
		this.accreditations = accreditations;
	}

	public String getJcpoffices() {
		return this.jcpoffices;
	}

	public void setJcpoffices(String jcpoffices) {
		this.jcpoffices = jcpoffices;
	}

	public String getLocalDemographicIssue() {
		return this.localDemographicIssue;
	}

	public void setLocalDemographicIssue(String localDemographicIssue) {
		this.localDemographicIssue = localDemographicIssue;
	}

	public Integer getIsnetwork() {
		return this.isnetwork;
	}

	public void setIsnetwork(Integer isnetwork) {
		this.isnetwork = isnetwork;
	}

	public Boolean getRoomAvailability() {
		return this.roomAvailability;
	}

	public void setRoomAvailability(Boolean roomAvailability) {
		this.roomAvailability = roomAvailability;
	}

	public Boolean getVolunteeringOpportunities() {
		return this.volunteeringOpportunities;
	}

	public void setVolunteeringOpportunities(Boolean volunteeringOpportunities) {
		this.volunteeringOpportunities = volunteeringOpportunities;
	}

	public String getOutreachLocation() {
		return this.outreachLocation;
	}

	public void setOutreachLocation(String outreachLocation) {
		this.outreachLocation = outreachLocation;
	}

	public String getLocalHotel() {
		return this.localHotel;
	}

	public void setLocalHotel(String localHotel) {
		this.localHotel = localHotel;
	}

	public String getTravelDetails() {
		return this.travelDetails;
	}

	public void setTravelDetails(String travelDetails) {
		this.travelDetails = travelDetails;
	}

	public Boolean getVisitorParkingOnsite() {
		return this.visitorParkingOnsite;
	}

	public void setVisitorParkingOnsite(Boolean visitorParkingOnsite) {
		this.visitorParkingOnsite = visitorParkingOnsite;
	}

	public String getTravelNearestBus() {
		return this.travelNearestBus;
	}

	public void setTravelNearestBus(String travelNearestBus) {
		this.travelNearestBus = travelNearestBus;
	}

	public Boolean getHostVisits() {
		return this.hostVisits;
	}

	public void setHostVisits(Boolean hostVisits) {
		this.hostVisits = hostVisits;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Double getRoomOnlyRate() {
		return this.roomOnlyRate;
	}

	public void setRoomOnlyRate(Double roomOnlyRate) {
		this.roomOnlyRate = roomOnlyRate;
	}

	public Double getNegotiatedRoomOnlyRate() {
		return this.negotiatedRoomOnlyRate;
	}

	public void setNegotiatedRoomOnlyRate(Double negotiatedRoomOnlyRate) {
		this.negotiatedRoomOnlyRate = negotiatedRoomOnlyRate;
	}

	public Double getBbrate() {
		return this.bbrate;
	}

	public void setBbrate(Double bbrate) {
		this.bbrate = bbrate;
	}

	public Double getBbnegotiatedRate() {
		return this.bbnegotiatedRate;
	}

	public void setBbnegotiatedRate(Double bbnegotiatedRate) {
		this.bbnegotiatedRate = bbnegotiatedRate;
	}

	public Boolean getLunch() {
		return this.lunch;
	}

	public void setLunch(Boolean lunch) {
		this.lunch = lunch;
	}

	public Date getLastNegotiatedDate() {
		return this.lastNegotiatedDate;
	}

	public void setLastNegotiatedDate(Date lastNegotiatedDate) {
		this.lastNegotiatedDate = lastNegotiatedDate;
	}

	public Date getReNegotiatedOn() {
		return this.reNegotiatedOn;
	}

	public void setReNegotiatedOn(Date reNegotiatedOn) {
		this.reNegotiatedOn = reNegotiatedOn;
	}

	public Integer getNoOfMeetingRoom() {
		return this.noOfMeetingRoom;
	}

	public void setNoOfMeetingRoom(Integer noOfMeetingRoom) {
		this.noOfMeetingRoom = noOfMeetingRoom;
	}

	public Double getMeetingRoomRatePerDay() {
		return this.meetingRoomRatePerDay;
	}

	public void setMeetingRoomRatePerDay(Double meetingRoomRatePerDay) {
		this.meetingRoomRatePerDay = meetingRoomRatePerDay;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
