package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * Programme generated by hbm2java
 */
public class Programme implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int programmeId;
	private Contact contact;
	private String name;
	private String description;
	private Boolean status;
	private Set<Service> services = new HashSet<Service>(0);

	public Programme() {
	}

	public Programme(int programmeId) {
		this.programmeId = programmeId;
	}

	public Programme(int programmeId, Contact contact, String name,
			String description, Boolean status, Set<Service> services) {
		this.programmeId = programmeId;
		this.contact = contact;
		this.name = name;
		this.description = description;
		this.status = status;
		this.services = services;
	}

	public int getProgrammeId() {
		return this.programmeId;
	}

	public void setProgrammeId(int programmeId) {
		this.programmeId = programmeId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
