package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * ReferenceType generated by hbm2java
 */
public class ReferenceType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int refTypeId;
	private String refTypeName;
	private Set<ReferenceData> referenceDatas = new HashSet<ReferenceData>(0);

	public ReferenceType() {
	}

	public ReferenceType(int refTypeId) {
		this.refTypeId = refTypeId;
	}

	public ReferenceType(int refTypeId, String refTypeName,
			Set<ReferenceData> referenceDatas) {
		this.refTypeId = refTypeId;
		this.refTypeName = refTypeName;
		this.referenceDatas = referenceDatas;
	}

	public int getRefTypeId() {
		return this.refTypeId;
	}

	public void setRefTypeId(int refTypeId) {
		this.refTypeId = refTypeId;
	}

	public String getRefTypeName() {
		return this.refTypeName;
	}

	public void setRefTypeName(String refTypeName) {
		this.refTypeName = refTypeName;
	}

	public Set<ReferenceData> getReferenceDatas() {
		return this.referenceDatas;
	}

	public void setReferenceDatas(Set<ReferenceData> referenceDatas) {
		this.referenceDatas = referenceDatas;
	}

}
