package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA



/**
 * ReferenceData generated by hbm2java
 */
public class ReferenceData  implements java.io.Serializable {


     private int referenceDataId;
     private String refType;
     private String value;

    public ReferenceData() {
    }

	
    public ReferenceData(int referenceDataId, String refType) {
        this.referenceDataId = referenceDataId;
        this.refType = refType;
    }
    public ReferenceData(int referenceDataId, String refType, String value) {
       this.referenceDataId = referenceDataId;
       this.refType = refType;
       this.value = value;
    }
   
    public int getReferenceDataId() {
        return this.referenceDataId;
    }
    
    public void setReferenceDataId(int referenceDataId) {
        this.referenceDataId = referenceDataId;
    }
    public String getRefType() {
        return this.refType;
    }
    
    public void setRefType(String refType) {
        this.refType = refType;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


