package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Services generated by hbm2java
 */
public class Services implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int serviceId;
	private ReferenceData referenceDataByServiceType;
	private ReferenceData referenceDataByServiceSubType;
	private String name;
	private String shortDescription;
	private Integer contactId;
	private Boolean isActive;
	private String fullDescription;
	private Integer departmentId;
	private String clientDescription;
	private String descriptionDelivery;
	private String serviceAttendace;
	private Date serviceStartExpected;
	private Date serviceStart;
	private Date serviceEnd;
	private Boolean serviceExtendable;
	private String serviceContractCode;
	private Double serviceContactValue;
	private Boolean contractStagedPayment;
	private String referralProcessMethod;
	private Boolean serviceTimeLimited;
	private Integer serviceTimeLimitedMonth;
	private Integer serviceExtendableMonth;
	private String serBenCrit;
	private String serBarCrit;
	private String serEthCrit;
	private String serDisCrit;
	private String serPerCirCrit;
	private String serOrtherCrit;
	private String clientSupportProcess;
	private String clientOutcome;
	private String intervention;
	private String targetClient;
	private String clientJourney;
	private String accreditation;
	private String otherService;
	private String referralSources;
	private Integer programmeId;
	private String supportCenters;
	private String contractOutcome;
	private String participartion;
	private String contractObligation;
	private Set<OrganisationService> organisationServices = new HashSet<OrganisationService>(
			0);
	private Set<ServicePremise> servicePremises = new HashSet<ServicePremise>(0);

	public Services() {
		super();
	}

	public Services(int serviceId) {
		super();
		this.serviceId = serviceId;
	}

	public Services(int serviceId, ReferenceData referenceDataByServiceType,
			ReferenceData referenceDataByServiceSubType, String name,
			String shortDescription, Integer contactId, Boolean isActive,
			String fullDescription, Integer departmentId,
			String clientDescription, String descriptionDelivery,
			String serviceAttendace, Date serviceStartExpected,
			Date serviceStart, Date serviceEnd, Boolean serviceExtendable,
			String serviceContractCode, Double serviceContactValue,
			Boolean contractStagedPayment, String referralProcessMethod,
			Boolean serviceTimeLimited, Integer serviceTimeLimitedMonth,
			Integer serviceExtendableMonth, String serBenCrit,
			String serBarCrit, String serEthCrit, String serDisCrit,
			String serPerCirCrit, String serOrtherCrit,
			String clientSupportProcess, String clientOutcome,
			String intervention, String targetClient, String clientJourney,
			String accreditation, String otherService, String referralSources,
			Integer programmeId, String supportCenters, String contractOutcome,
			String participartion, String contractObligation,
			Set<OrganisationService> organisationServices,
			Set<ServicePremise> servicePremises) {
		super();
		this.serviceId = serviceId;
		this.referenceDataByServiceType = referenceDataByServiceType;
		this.referenceDataByServiceSubType = referenceDataByServiceSubType;
		this.name = name;
		this.shortDescription = shortDescription;
		this.contactId = contactId;
		this.isActive = isActive;
		this.fullDescription = fullDescription;
		this.departmentId = departmentId;
		this.clientDescription = clientDescription;
		this.descriptionDelivery = descriptionDelivery;
		this.serviceAttendace = serviceAttendace;
		this.serviceStartExpected = serviceStartExpected;
		this.serviceStart = serviceStart;
		this.serviceEnd = serviceEnd;
		this.serviceExtendable = serviceExtendable;
		this.serviceContractCode = serviceContractCode;
		this.serviceContactValue = serviceContactValue;
		this.contractStagedPayment = contractStagedPayment;
		this.referralProcessMethod = referralProcessMethod;
		this.serviceTimeLimited = serviceTimeLimited;
		this.serviceTimeLimitedMonth = serviceTimeLimitedMonth;
		this.serviceExtendableMonth = serviceExtendableMonth;
		this.serBenCrit = serBenCrit;
		this.serBarCrit = serBarCrit;
		this.serEthCrit = serEthCrit;
		this.serDisCrit = serDisCrit;
		this.serPerCirCrit = serPerCirCrit;
		this.serOrtherCrit = serOrtherCrit;
		this.clientSupportProcess = clientSupportProcess;
		this.clientOutcome = clientOutcome;
		this.intervention = intervention;
		this.targetClient = targetClient;
		this.clientJourney = clientJourney;
		this.accreditation = accreditation;
		this.otherService = otherService;
		this.referralSources = referralSources;
		this.programmeId = programmeId;
		this.supportCenters = supportCenters;
		this.contractOutcome = contractOutcome;
		this.participartion = participartion;
		this.contractObligation = contractObligation;
		this.organisationServices = organisationServices;
		this.servicePremises = servicePremises;
	}

	public int getServiceId() {
		return serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	public ReferenceData getReferenceDataByServiceType() {
		return referenceDataByServiceType;
	}

	public void setReferenceDataByServiceType(
			ReferenceData referenceDataByServiceType) {
		this.referenceDataByServiceType = referenceDataByServiceType;
	}

	public ReferenceData getReferenceDataByServiceSubType() {
		return referenceDataByServiceSubType;
	}

	public void setReferenceDataByServiceSubType(
			ReferenceData referenceDataByServiceSubType) {
		this.referenceDataByServiceSubType = referenceDataByServiceSubType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDescription() {
		return shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public Integer getContactId() {
		return contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getFullDescription() {
		return fullDescription;
	}

	public void setFullDescription(String fullDescription) {
		this.fullDescription = fullDescription;
	}

	public Integer getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public String getClientDescription() {
		return clientDescription;
	}

	public void setClientDescription(String clientDescription) {
		this.clientDescription = clientDescription;
	}

	public String getDescriptionDelivery() {
		return descriptionDelivery;
	}

	public void setDescriptionDelivery(String descriptionDelivery) {
		this.descriptionDelivery = descriptionDelivery;
	}

	public String getServiceAttendace() {
		return serviceAttendace;
	}

	public void setServiceAttendace(String serviceAttendace) {
		this.serviceAttendace = serviceAttendace;
	}

	public Date getServiceStartExpected() {
		return serviceStartExpected;
	}

	public void setServiceStartExpected(Date serviceStartExpected) {
		this.serviceStartExpected = serviceStartExpected;
	}

	public Date getServiceStart() {
		return serviceStart;
	}

	public void setServiceStart(Date serviceStart) {
		this.serviceStart = serviceStart;
	}

	public Date getServiceEnd() {
		return serviceEnd;
	}

	public void setServiceEnd(Date serviceEnd) {
		this.serviceEnd = serviceEnd;
	}

	public Boolean getServiceExtendable() {
		return serviceExtendable;
	}

	public void setServiceExtendable(Boolean serviceExtendable) {
		this.serviceExtendable = serviceExtendable;
	}

	public String getServiceContractCode() {
		return serviceContractCode;
	}

	public void setServiceContractCode(String serviceContractCode) {
		this.serviceContractCode = serviceContractCode;
	}

	public Double getServiceContactValue() {
		return serviceContactValue;
	}

	public void setServiceContactValue(Double serviceContactValue) {
		this.serviceContactValue = serviceContactValue;
	}

	public Boolean getContractStagedPayment() {
		return contractStagedPayment;
	}

	public void setContractStagedPayment(Boolean contractStagedPayment) {
		this.contractStagedPayment = contractStagedPayment;
	}

	public String getReferralProcessMethod() {
		return referralProcessMethod;
	}

	public void setReferralProcessMethod(String referralProcessMethod) {
		this.referralProcessMethod = referralProcessMethod;
	}

	public Boolean getServiceTimeLimited() {
		return serviceTimeLimited;
	}

	public void setServiceTimeLimited(Boolean serviceTimeLimited) {
		this.serviceTimeLimited = serviceTimeLimited;
	}

	public Integer getServiceTimeLimitedMonth() {
		return serviceTimeLimitedMonth;
	}

	public void setServiceTimeLimitedMonth(Integer serviceTimeLimitedMonth) {
		this.serviceTimeLimitedMonth = serviceTimeLimitedMonth;
	}

	public Integer getServiceExtendableMonth() {
		return serviceExtendableMonth;
	}

	public void setServiceExtendableMonth(Integer serviceExtendableMonth) {
		this.serviceExtendableMonth = serviceExtendableMonth;
	}

	public String getSerBenCrit() {
		return serBenCrit;
	}

	public void setSerBenCrit(String serBenCrit) {
		this.serBenCrit = serBenCrit;
	}

	public String getSerBarCrit() {
		return serBarCrit;
	}

	public void setSerBarCrit(String serBarCrit) {
		this.serBarCrit = serBarCrit;
	}

	public String getSerEthCrit() {
		return serEthCrit;
	}

	public void setSerEthCrit(String serEthCrit) {
		this.serEthCrit = serEthCrit;
	}

	public String getSerDisCrit() {
		return serDisCrit;
	}

	public void setSerDisCrit(String serDisCrit) {
		this.serDisCrit = serDisCrit;
	}

	public String getSerPerCirCrit() {
		return serPerCirCrit;
	}

	public void setSerPerCirCrit(String serPerCirCrit) {
		this.serPerCirCrit = serPerCirCrit;
	}

	public String getSerOrtherCrit() {
		return serOrtherCrit;
	}

	public void setSerOrtherCrit(String serOrtherCrit) {
		this.serOrtherCrit = serOrtherCrit;
	}

	public String getClientSupportProcess() {
		return clientSupportProcess;
	}

	public void setClientSupportProcess(String clientSupportProcess) {
		this.clientSupportProcess = clientSupportProcess;
	}

	public String getClientOutcome() {
		return clientOutcome;
	}

	public void setClientOutcome(String clientOutcome) {
		this.clientOutcome = clientOutcome;
	}

	public String getIntervention() {
		return intervention;
	}

	public void setIntervention(String intervention) {
		this.intervention = intervention;
	}

	public String getTargetClient() {
		return targetClient;
	}

	public void setTargetClient(String targetClient) {
		this.targetClient = targetClient;
	}

	public String getClientJourney() {
		return clientJourney;
	}

	public void setClientJourney(String clientJourney) {
		this.clientJourney = clientJourney;
	}

	public String getAccreditation() {
		return accreditation;
	}

	public void setAccreditation(String accreditation) {
		this.accreditation = accreditation;
	}

	public String getOtherService() {
		return otherService;
	}

	public void setOtherService(String otherService) {
		this.otherService = otherService;
	}

	public String getReferralSources() {
		return referralSources;
	}

	public void setReferralSources(String referralSources) {
		this.referralSources = referralSources;
	}

	public Integer getProgrammeId() {
		return programmeId;
	}

	public void setProgrammeId(Integer programmeId) {
		this.programmeId = programmeId;
	}

	public String getSupportCenters() {
		return supportCenters;
	}

	public void setSupportCenters(String supportCenters) {
		this.supportCenters = supportCenters;
	}

	public String getContractOutcome() {
		return contractOutcome;
	}

	public void setContractOutcome(String contractOutcome) {
		this.contractOutcome = contractOutcome;
	}

	public String getParticipartion() {
		return participartion;
	}

	public void setParticipartion(String participartion) {
		this.participartion = participartion;
	}

	public String getContractObligation() {
		return contractObligation;
	}

	public void setContractObligation(String contractObligation) {
		this.contractObligation = contractObligation;
	}

	public Set<OrganisationService> getOrganisationServices() {
		return organisationServices;
	}

	public void setOrganisationServices(
			Set<OrganisationService> organisationServices) {
		this.organisationServices = organisationServices;
	}

	public Set<ServicePremise> getServicePremises() {
		return servicePremises;
	}

	public void setServicePremises(Set<ServicePremise> servicePremises) {
		this.servicePremises = servicePremises;
	}

}
