package fsoft.xdev.mock.models;
import java.util.Date;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int serviceId;
	private Contact contact;
	private ReferenceData referenceDataByServiceType;
	private ReferenceData referenceDataByServiceSubType;
	private Programme programme;
	private String name;
	private String shortDescription;
	private Boolean status;
	private String fullDescription;
	private Integer departmentId;
	private String clientDescription;
	private String descriptionDelivery;
	private String serviceAttendace;
	private Date serviceStartExpected;
	private Date serviceStart;
	private Date serviceEnd;
	private Boolean serviceExtendable;
	private String serviceContractCode;
	private Double serviceContactValue;
	private Boolean contractStagedPayment;
	private String referralProcessMethod;
	private Boolean serviceTimeLimited;
	private Integer serviceTimeLimitedMonth;
	private Integer serviceExtendableMonth;
	private String serBenCrit;
	private String serBarCrit;
	private String serEthCrit;
	private String serDisCrit;
	private String serPerCirCrit;
	private String serOrtherCrit;
	private String clientSupportProcess;
	private String clientOutcome;
	private String intervention;
	private String targetClient;
	private String clientJourney;
	private String accreditation;
	private String otherService;
	private String referralSources;
	private String supportCenters;
	private String contractOutcome;
	private String participartion;
	private String contractObligation;

	public Service() {
	}

	public Service(int serviceId) {
		this.serviceId = serviceId;
	}

	public Service(int serviceId, Contact contact,
			ReferenceData referenceDataByServiceType,
			ReferenceData referenceDataByServiceSubType, Programme programme,
			String name, String shortDescription, Boolean status,
			String fullDescription, Integer departmentId,
			String clientDescription, String descriptionDelivery,
			String serviceAttendace, Date serviceStartExpected,
			Date serviceStart, Date serviceEnd, Boolean serviceExtendable,
			String serviceContractCode, Double serviceContactValue,
			Boolean contractStagedPayment, String referralProcessMethod,
			Boolean serviceTimeLimited, Integer serviceTimeLimitedMonth,
			Integer serviceExtendableMonth, String serBenCrit,
			String serBarCrit, String serEthCrit, String serDisCrit,
			String serPerCirCrit, String serOrtherCrit,
			String clientSupportProcess, String clientOutcome,
			String intervention, String targetClient, String clientJourney,
			String accreditation, String otherService, String referralSources,
			String supportCenters, String contractOutcome,
			String participartion, String contractObligation) {
		this.serviceId = serviceId;
		this.contact = contact;
		this.referenceDataByServiceType = referenceDataByServiceType;
		this.referenceDataByServiceSubType = referenceDataByServiceSubType;
		this.programme = programme;
		this.name = name;
		this.shortDescription = shortDescription;
		this.status = status;
		this.fullDescription = fullDescription;
		this.departmentId = departmentId;
		this.clientDescription = clientDescription;
		this.descriptionDelivery = descriptionDelivery;
		this.serviceAttendace = serviceAttendace;
		this.serviceStartExpected = serviceStartExpected;
		this.serviceStart = serviceStart;
		this.serviceEnd = serviceEnd;
		this.serviceExtendable = serviceExtendable;
		this.serviceContractCode = serviceContractCode;
		this.serviceContactValue = serviceContactValue;
		this.contractStagedPayment = contractStagedPayment;
		this.referralProcessMethod = referralProcessMethod;
		this.serviceTimeLimited = serviceTimeLimited;
		this.serviceTimeLimitedMonth = serviceTimeLimitedMonth;
		this.serviceExtendableMonth = serviceExtendableMonth;
		this.serBenCrit = serBenCrit;
		this.serBarCrit = serBarCrit;
		this.serEthCrit = serEthCrit;
		this.serDisCrit = serDisCrit;
		this.serPerCirCrit = serPerCirCrit;
		this.serOrtherCrit = serOrtherCrit;
		this.clientSupportProcess = clientSupportProcess;
		this.clientOutcome = clientOutcome;
		this.intervention = intervention;
		this.targetClient = targetClient;
		this.clientJourney = clientJourney;
		this.accreditation = accreditation;
		this.otherService = otherService;
		this.referralSources = referralSources;
		this.supportCenters = supportCenters;
		this.contractOutcome = contractOutcome;
		this.participartion = participartion;
		this.contractObligation = contractObligation;
	}

	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public ReferenceData getReferenceDataByServiceType() {
		return this.referenceDataByServiceType;
	}

	public void setReferenceDataByServiceType(
			ReferenceData referenceDataByServiceType) {
		this.referenceDataByServiceType = referenceDataByServiceType;
	}

	public ReferenceData getReferenceDataByServiceSubType() {
		return this.referenceDataByServiceSubType;
	}

	public void setReferenceDataByServiceSubType(
			ReferenceData referenceDataByServiceSubType) {
		this.referenceDataByServiceSubType = referenceDataByServiceSubType;
	}

	public Programme getProgramme() {
		return this.programme;
	}

	public void setProgramme(Programme programme) {
		this.programme = programme;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getFullDescription() {
		return this.fullDescription;
	}

	public void setFullDescription(String fullDescription) {
		this.fullDescription = fullDescription;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public String getClientDescription() {
		return this.clientDescription;
	}

	public void setClientDescription(String clientDescription) {
		this.clientDescription = clientDescription;
	}

	public String getDescriptionDelivery() {
		return this.descriptionDelivery;
	}

	public void setDescriptionDelivery(String descriptionDelivery) {
		this.descriptionDelivery = descriptionDelivery;
	}

	public String getServiceAttendace() {
		return this.serviceAttendace;
	}

	public void setServiceAttendace(String serviceAttendace) {
		this.serviceAttendace = serviceAttendace;
	}

	public Date getServiceStartExpected() {
		return this.serviceStartExpected;
	}

	public void setServiceStartExpected(Date serviceStartExpected) {
		this.serviceStartExpected = serviceStartExpected;
	}

	public Date getServiceStart() {
		return this.serviceStart;
	}

	public void setServiceStart(Date serviceStart) {
		this.serviceStart = serviceStart;
	}

	public Date getServiceEnd() {
		return this.serviceEnd;
	}

	public void setServiceEnd(Date serviceEnd) {
		this.serviceEnd = serviceEnd;
	}

	public Boolean getServiceExtendable() {
		return this.serviceExtendable;
	}

	public void setServiceExtendable(Boolean serviceExtendable) {
		this.serviceExtendable = serviceExtendable;
	}

	public String getServiceContractCode() {
		return this.serviceContractCode;
	}

	public void setServiceContractCode(String serviceContractCode) {
		this.serviceContractCode = serviceContractCode;
	}

	public Double getServiceContactValue() {
		return this.serviceContactValue;
	}

	public void setServiceContactValue(Double serviceContactValue) {
		this.serviceContactValue = serviceContactValue;
	}

	public Boolean getContractStagedPayment() {
		return this.contractStagedPayment;
	}

	public void setContractStagedPayment(Boolean contractStagedPayment) {
		this.contractStagedPayment = contractStagedPayment;
	}

	public String getReferralProcessMethod() {
		return this.referralProcessMethod;
	}

	public void setReferralProcessMethod(String referralProcessMethod) {
		this.referralProcessMethod = referralProcessMethod;
	}

	public Boolean getServiceTimeLimited() {
		return this.serviceTimeLimited;
	}

	public void setServiceTimeLimited(Boolean serviceTimeLimited) {
		this.serviceTimeLimited = serviceTimeLimited;
	}

	public Integer getServiceTimeLimitedMonth() {
		return this.serviceTimeLimitedMonth;
	}

	public void setServiceTimeLimitedMonth(Integer serviceTimeLimitedMonth) {
		this.serviceTimeLimitedMonth = serviceTimeLimitedMonth;
	}

	public Integer getServiceExtendableMonth() {
		return this.serviceExtendableMonth;
	}

	public void setServiceExtendableMonth(Integer serviceExtendableMonth) {
		this.serviceExtendableMonth = serviceExtendableMonth;
	}

	public String getSerBenCrit() {
		return this.serBenCrit;
	}

	public void setSerBenCrit(String serBenCrit) {
		this.serBenCrit = serBenCrit;
	}

	public String getSerBarCrit() {
		return this.serBarCrit;
	}

	public void setSerBarCrit(String serBarCrit) {
		this.serBarCrit = serBarCrit;
	}

	public String getSerEthCrit() {
		return this.serEthCrit;
	}

	public void setSerEthCrit(String serEthCrit) {
		this.serEthCrit = serEthCrit;
	}

	public String getSerDisCrit() {
		return this.serDisCrit;
	}

	public void setSerDisCrit(String serDisCrit) {
		this.serDisCrit = serDisCrit;
	}

	public String getSerPerCirCrit() {
		return this.serPerCirCrit;
	}

	public void setSerPerCirCrit(String serPerCirCrit) {
		this.serPerCirCrit = serPerCirCrit;
	}

	public String getSerOrtherCrit() {
		return this.serOrtherCrit;
	}

	public void setSerOrtherCrit(String serOrtherCrit) {
		this.serOrtherCrit = serOrtherCrit;
	}

	public String getClientSupportProcess() {
		return this.clientSupportProcess;
	}

	public void setClientSupportProcess(String clientSupportProcess) {
		this.clientSupportProcess = clientSupportProcess;
	}

	public String getClientOutcome() {
		return this.clientOutcome;
	}

	public void setClientOutcome(String clientOutcome) {
		this.clientOutcome = clientOutcome;
	}

	public String getIntervention() {
		return this.intervention;
	}

	public void setIntervention(String intervention) {
		this.intervention = intervention;
	}

	public String getTargetClient() {
		return this.targetClient;
	}

	public void setTargetClient(String targetClient) {
		this.targetClient = targetClient;
	}

	public String getClientJourney() {
		return this.clientJourney;
	}

	public void setClientJourney(String clientJourney) {
		this.clientJourney = clientJourney;
	}

	public String getAccreditation() {
		return this.accreditation;
	}

	public void setAccreditation(String accreditation) {
		this.accreditation = accreditation;
	}

	public String getOtherService() {
		return this.otherService;
	}

	public void setOtherService(String otherService) {
		this.otherService = otherService;
	}

	public String getReferralSources() {
		return this.referralSources;
	}

	public void setReferralSources(String referralSources) {
		this.referralSources = referralSources;
	}

	public String getSupportCenters() {
		return this.supportCenters;
	}

	public void setSupportCenters(String supportCenters) {
		this.supportCenters = supportCenters;
	}

	public String getContractOutcome() {
		return this.contractOutcome;
	}

	public void setContractOutcome(String contractOutcome) {
		this.contractOutcome = contractOutcome;
	}

	public String getParticipartion() {
		return this.participartion;
	}

	public void setParticipartion(String participartion) {
		this.participartion = participartion;
	}

	public String getContractObligation() {
		return this.contractObligation;
	}

	public void setContractObligation(String contractObligation) {
		this.contractObligation = contractObligation;
	}

}
