package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

/**
 * Teams generated by hbm2java
 */
public class Teams implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int teamId;
	private Departments departments;
	private Contacts contacts;
	private TypeOfBusiness typeOfBusiness;
	private String name;
	private String shortDesc;
	private Boolean copyAddr;
	private String addr1;
	private String addr2;
	private String addr3;
	private String postCode;
	private String town;
	private String county;
	private String country;
	private String fullDesc;
	private String phoneNumber;
	private String fax;
	private String email;
	private String webAddr;
	private Boolean isActive;

	public Teams() {
	}

	public Teams(int teamId) {
		this.teamId = teamId;
	}

	public Teams(int teamId, Departments departments, Contacts contacts,
			TypeOfBusiness typeOfBusiness, String name, String shortDesc,
			Boolean copyAddr, String addr1, String addr2, String addr3,
			String postCode, String town, String county, String country,
			String fullDesc, String phoneNumber, String fax, String email,
			String webAddr, Boolean isActive) {
		this.teamId = teamId;
		this.departments = departments;
		this.contacts = contacts;
		this.typeOfBusiness = typeOfBusiness;
		this.name = name;
		this.shortDesc = shortDesc;
		this.copyAddr = copyAddr;
		this.addr1 = addr1;
		this.addr2 = addr2;
		this.addr3 = addr3;
		this.postCode = postCode;
		this.town = town;
		this.county = county;
		this.country = country;
		this.fullDesc = fullDesc;
		this.phoneNumber = phoneNumber;
		this.fax = fax;
		this.email = email;
		this.webAddr = webAddr;
		this.isActive = isActive;
	}

	public int getTeamId() {
		return this.teamId;
	}

	public void setTeamId(int teamId) {
		this.teamId = teamId;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public TypeOfBusiness getTypeOfBusiness() {
		return this.typeOfBusiness;
	}

	public void setTypeOfBusiness(TypeOfBusiness typeOfBusiness) {
		this.typeOfBusiness = typeOfBusiness;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public Boolean getCopyAddr() {
		return this.copyAddr;
	}

	public void setCopyAddr(Boolean copyAddr) {
		this.copyAddr = copyAddr;
	}

	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getFullDesc() {
		return this.fullDesc;
	}

	public void setFullDesc(String fullDesc) {
		this.fullDesc = fullDesc;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebAddr() {
		return this.webAddr;
	}

	public void setWebAddr(String webAddr) {
		this.webAddr = webAddr;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
