package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * Town generated by hbm2java
 */
public class Town implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int townId;
	private County county;
	private String name;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Town() {
	}

	public Town(int townId) {
		this.townId = townId;
	}

	public Town(int townId, County county, String name, Set<Address> addresses) {
		this.townId = townId;
		this.county = county;
		this.name = name;
		this.addresses = addresses;
	}

	public int getTownId() {
		return this.townId;
	}

	public void setTownId(int townId) {
		this.townId = townId;
	}

	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
