package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TrustRegions generated by hbm2java
 */
public class TrustRegions implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int trustRegionId;
	private Countries countries;
	private String name;
	private String description;
	private Boolean isActive;
	private Set<TrustDistricts> trustDistrictses = new HashSet<TrustDistricts>(
			0);

	public TrustRegions() {
	}

	public TrustRegions(int trustRegionId) {
		this.trustRegionId = trustRegionId;
	}

	public TrustRegions(int trustRegionId, Countries countries, String name,
			String description, Boolean isActive,
			Set<TrustDistricts> trustDistrictses) {
		this.trustRegionId = trustRegionId;
		this.countries = countries;
		this.name = name;
		this.description = description;
		this.isActive = isActive;
		this.trustDistrictses = trustDistrictses;
	}

	public int getTrustRegionId() {
		return this.trustRegionId;
	}

	public void setTrustRegionId(int trustRegionId) {
		this.trustRegionId = trustRegionId;
	}

	public Countries getCountries() {
		return this.countries;
	}

	public void setCountries(Countries countries) {
		this.countries = countries;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<TrustDistricts> getTrustDistrictses() {
		return this.trustDistrictses;
	}

	public void setTrustDistrictses(Set<TrustDistricts> trustDistrictses) {
		this.trustDistrictses = trustDistrictses;
	}

}
