package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * TrustDistrict generated by hbm2java
 */
public class TrustDistrict implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int trustDistrictId;
	private TrustRegion trustRegion;
	private String name;
	private String description;
	private Boolean status;
	private Set<Organisation> organisations = new HashSet<Organisation>(0);

	public TrustDistrict() {
	}

	public TrustDistrict(int trustDistrictId) {
		this.trustDistrictId = trustDistrictId;
	}

	public TrustDistrict(int trustDistrictId, TrustRegion trustRegion,
			String name, String description, Boolean status,
			Set<Organisation> organisations) {
		this.trustDistrictId = trustDistrictId;
		this.trustRegion = trustRegion;
		this.name = name;
		this.description = description;
		this.status = status;
		this.organisations = organisations;
	}

	public int getTrustDistrictId() {
		return this.trustDistrictId;
	}

	public void setTrustDistrictId(int trustDistrictId) {
		this.trustDistrictId = trustDistrictId;
	}

	public TrustRegion getTrustRegion() {
		return this.trustRegion;
	}

	public void setTrustRegion(TrustRegion trustRegion) {
		this.trustRegion = trustRegion;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

}
