package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TrustRegions generated by hbm2java
 */
public class TrustRegions  implements java.io.Serializable {


     private int trustRegionId;
     private Countries countries;
     private String name;
     private String description;
     private boolean isActive;
     private Set trustDistrictses = new HashSet(0);

    public TrustRegions() {
    }

	
    public TrustRegions(int trustRegionId, Countries countries, String name, boolean isActive) {
        this.trustRegionId = trustRegionId;
        this.countries = countries;
        this.name = name;
        this.isActive = isActive;
    }
    public TrustRegions(int trustRegionId, Countries countries, String name, String description, boolean isActive, Set trustDistrictses) {
       this.trustRegionId = trustRegionId;
       this.countries = countries;
       this.name = name;
       this.description = description;
       this.isActive = isActive;
       this.trustDistrictses = trustDistrictses;
    }
   
    public int getTrustRegionId() {
        return this.trustRegionId;
    }
    
    public void setTrustRegionId(int trustRegionId) {
        this.trustRegionId = trustRegionId;
    }
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
    public Set getTrustDistrictses() {
        return this.trustDistrictses;
    }
    
    public void setTrustDistrictses(Set trustDistrictses) {
        this.trustDistrictses = trustDistrictses;
    }




}


