package fsoft.xdev.mock.models;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeOfBusiness generated by hbm2java
 */
public class TypeOfBusiness implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int typeOfBusinessId;
	private String name;
	private String sicCode;
	private Set<Team> teams = new HashSet<Team>(0);
	private Set<Organisation> organisations = new HashSet<Organisation>(0);
	private Set<Department> departments = new HashSet<Department>(0);
	private Set<Directorate> directorates = new HashSet<Directorate>(0);

	public TypeOfBusiness() {
	}

	public TypeOfBusiness(int typeOfBusinessId) {
		this.typeOfBusinessId = typeOfBusinessId;
	}

	public TypeOfBusiness(int typeOfBusinessId, String name, String sicCode,
			Set<Team> teams, Set<Organisation> organisations,
			Set<Department> departments, Set<Directorate> directorates) {
		this.typeOfBusinessId = typeOfBusinessId;
		this.name = name;
		this.sicCode = sicCode;
		this.teams = teams;
		this.organisations = organisations;
		this.departments = departments;
		this.directorates = directorates;
	}

	public int getTypeOfBusinessId() {
		return this.typeOfBusinessId;
	}

	public void setTypeOfBusinessId(int typeOfBusinessId) {
		this.typeOfBusinessId = typeOfBusinessId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSicCode() {
		return this.sicCode;
	}

	public void setSicCode(String sicCode) {
		this.sicCode = sicCode;
	}

	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

	public Set<Organisation> getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Set<Organisation> organisations) {
		this.organisations = organisations;
	}

	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

	public Set<Directorate> getDirectorates() {
		return this.directorates;
	}

	public void setDirectorates(Set<Directorate> directorates) {
		this.directorates = directorates;
	}

}
