package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int userId;
	private String userName;
	private String password;
	private String email;
	private Integer permission;
	private Set<SupportingMaterials> supportingMaterialses = new HashSet<SupportingMaterials>(
			0);

	public Users() {
	}

	public Users(int userId) {
		this.userId = userId;
	}

	public Users(int userId, String userName, String password, String email,
			Integer permission, Set<SupportingMaterials> supportingMaterialses) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.permission = permission;
		this.supportingMaterialses = supportingMaterialses;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getPermission() {
		return this.permission;
	}

	public void setPermission(Integer permission) {
		this.permission = permission;
	}

	public Set<SupportingMaterials> getSupportingMaterialses() {
		return this.supportingMaterialses;
	}

	public void setSupportingMaterialses(
			Set<SupportingMaterials> supportingMaterialses) {
		this.supportingMaterialses = supportingMaterialses;
	}

}
