package fsoft.xdev.mock.models;
// Generated Nov 29, 2011 3:23:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String password;
     private String email;
     private Integer permission;
     private Set supportingMaterialses = new HashSet(0);

    public Users() {
    }

	
    public Users(int userId, String userName, String password) {
        this.userId = userId;
        this.userName = userName;
        this.password = password;
    }
    public Users(int userId, String userName, String password, String email, Integer permission, Set supportingMaterialses) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.permission = permission;
       this.supportingMaterialses = supportingMaterialses;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getPermission() {
        return this.permission;
    }
    
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
    public Set getSupportingMaterialses() {
        return this.supportingMaterialses;
    }
    
    public void setSupportingMaterialses(Set supportingMaterialses) {
        this.supportingMaterialses = supportingMaterialses;
    }




}


