package fsoft.xdev.mock.models;

// Generated Dec 16, 2011 11:06:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Volunteer generated by hbm2java
 */
public class Volunteer implements java.io.Serializable {

	private int volunteerId;
	private Contact contact;
	private String volunteerPurpose;
	private String details;
	private Date startDate;
	private Date endDate;
	private Integer premiseId;
	private Integer volunteerNo;
	private Boolean status;

	public Volunteer() {
	}

	public Volunteer(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public Volunteer(int volunteerId, Contact contact, String volunteerPurpose,
			String details, Date startDate, Date endDate, Integer premiseId,
			Integer volunteerNo, Boolean status) {
		this.volunteerId = volunteerId;
		this.contact = contact;
		this.volunteerPurpose = volunteerPurpose;
		this.details = details;
		this.startDate = startDate;
		this.endDate = endDate;
		this.premiseId = premiseId;
		this.volunteerNo = volunteerNo;
		this.status = status;
	}

	public int getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public String getVolunteerPurpose() {
		return this.volunteerPurpose;
	}

	public void setVolunteerPurpose(String volunteerPurpose) {
		this.volunteerPurpose = volunteerPurpose;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getPremiseId() {
		return this.premiseId;
	}

	public void setPremiseId(Integer premiseId) {
		this.premiseId = premiseId;
	}

	public Integer getVolunteerNo() {
		return this.volunteerNo;
	}

	public void setVolunteerNo(Integer volunteerNo) {
		this.volunteerNo = volunteerNo;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
