<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns="http://www.dis-corp.com"
                  xmlns:typens="http://www.dis-corp.com"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://www.dis-corp.com">

  <wsdl:types>
    <xsd:schema targetNamespace="http://www.dis-corp.com" elementFormDefault="qualified">

      <xsd:import namespace="http://www.dis-corp.com"
                  schemaLocation="dealer.xsd"/>
                  
    </xsd:schema>

  </wsdl:types>

  <!-- Dealer -->
  <wsdl:message name="GetDealer">
    <wsdl:part name="payload" element="typens:GetDealer"/>
  </wsdl:message>  
  
  <!--
  	Define port type 
   -->
   
  <wsdl:portType name="EnterprisePortType">
  
    <wsdl:operation name="GetDealer">
      <wsdl:input message="GetDealer"/>
      <wsdl:output message="GetDealer"/>
    </wsdl:operation>
                      
  </wsdl:portType>  

  <!-- Binding service message with HTTP transporter -->
  <wsdl:binding name="EnterpriseSOAPBinding" type="EnterprisePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    
    <wsdl:operation name="GetDealer">
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    
  </wsdl:binding>

  <wsdl:service name="EnterpriseService">
    <wsdl:port name="EnterprisePort" binding="EnterpriseSOAPBinding" >
      <soap:address location="http://localhost:8181/enterprise"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>