package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

/**
 * Addresses generated by hbm2java
 */
public class Addresses implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int addressId;
	private Towns towns;
	private String name;
	private String postCode;

	public Addresses() {
	}

	public Addresses(int addressId) {
		this.addressId = addressId;
	}

	public Addresses(int addressId, Towns towns, String name, String postCode) {
		this.addressId = addressId;
		this.towns = towns;
		this.name = name;
		this.postCode = postCode;
	}

	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	public Towns getTowns() {
		return this.towns;
	}

	public void setTowns(Towns towns) {
		this.towns = towns;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

}
