package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

/**
 * OrganisationProgramme generated by hbm2java
 */
public class OrganisationProgramme implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Organisations organisations;
	private Programmes programmes;

	public OrganisationProgramme() {
	}

	public OrganisationProgramme(int id) {
		this.id = id;
	}

	public OrganisationProgramme(int id, Organisations organisations,
			Programmes programmes) {
		this.id = id;
		this.organisations = organisations;
		this.programmes = programmes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Organisations getOrganisations() {
		return this.organisations;
	}

	public void setOrganisations(Organisations organisations) {
		this.organisations = organisations;
	}

	public Programmes getProgrammes() {
		return this.programmes;
	}

	public void setProgrammes(Programmes programmes) {
		this.programmes = programmes;
	}

}
