package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TrustDistricts generated by hbm2java
 */
public class TrustDistricts implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int trustDistrictId;
	private TrustRegions trustRegions;
	private String name;
	private String description;
	private Boolean isActive;
	private Set<Organisations> organisationses = new HashSet<Organisations>(0);

	public TrustDistricts() {
	}

	public TrustDistricts(int trustDistrictId) {
		this.trustDistrictId = trustDistrictId;
	}

	public TrustDistricts(int trustDistrictId, TrustRegions trustRegions,
			String name, String description, Boolean isActive,
			Set<Organisations> organisationses) {
		this.trustDistrictId = trustDistrictId;
		this.trustRegions = trustRegions;
		this.name = name;
		this.description = description;
		this.isActive = isActive;
		this.organisationses = organisationses;
	}

	public int getTrustDistrictId() {
		return this.trustDistrictId;
	}

	public void setTrustDistrictId(int trustDistrictId) {
		this.trustDistrictId = trustDistrictId;
	}

	public TrustRegions getTrustRegions() {
		return this.trustRegions;
	}

	public void setTrustRegions(TrustRegions trustRegions) {
		this.trustRegions = trustRegions;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<Organisations> getOrganisationses() {
		return this.organisationses;
	}

	public void setOrganisationses(Set<Organisations> organisationses) {
		this.organisationses = organisationses;
	}

}
