package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TypeOfBusiness generated by hbm2java
 */
public class TypeOfBusiness implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int typeOfBusinessId;
	private String name;
	private String sicCode;
	private Set<Teams> teamses = new HashSet<Teams>(0);

	public TypeOfBusiness() {
	}

	public TypeOfBusiness(int typeOfBusinessId) {
		this.typeOfBusinessId = typeOfBusinessId;
	}

	public TypeOfBusiness(int typeOfBusinessId, String name, String sicCode,
			Set<Teams> teamses) {
		this.typeOfBusinessId = typeOfBusinessId;
		this.name = name;
		this.sicCode = sicCode;
		this.teamses = teamses;
	}

	public int getTypeOfBusinessId() {
		return this.typeOfBusinessId;
	}

	public void setTypeOfBusinessId(int typeOfBusinessId) {
		this.typeOfBusinessId = typeOfBusinessId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSicCode() {
		return this.sicCode;
	}

	public void setSicCode(String sicCode) {
		this.sicCode = sicCode;
	}

	public Set<Teams> getTeamses() {
		return this.teamses;
	}

	public void setTeamses(Set<Teams> teamses) {
		this.teamses = teamses;
	}

}
