package fsoft.xdev.mock.models;
// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Directorates generated by hbm2java
 */
public class Directorates  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private int directorateId;
     private Contacts contacts;
     private String name;
     private String shortDesc;
     private Boolean copyAddrOrg;
     private String addr1;
     private String addr2;
     private String addr3;
     private String postCode;
     private String town;
     private String countyId;
     private String countryId;
     private Integer typeOfBusinessId;
     private String fullDesc;
     private String phoneNumber;
     private String fax;
     private String email;
     private String webAddr;
     private String charityNumber;
     private String companyNumber;
     private Integer organisationId;
     private Boolean isActive;
     private Set<Departments> departmentses = new HashSet<Departments>(0);

    public Directorates() {
    }

	
    public Directorates(int directorateId) {
        this.directorateId = directorateId;
    }
    public Directorates(int directorateId, Contacts contacts, String name, String shortDesc, Boolean copyAddrOrg, String addr1, String addr2, String addr3, String postCode, String town, String countyId, String countryId, Integer typeOfBusinessId, String fullDesc, String phoneNumber, String fax, String email, String webAddr, String charityNumber, String companyNumber, Integer organisationId, Boolean isActive, Set<Departments> departmentses) {
       this.directorateId = directorateId;
       this.contacts = contacts;
       this.name = name;
       this.shortDesc = shortDesc;
       this.copyAddrOrg = copyAddrOrg;
       this.addr1 = addr1;
       this.addr2 = addr2;
       this.addr3 = addr3;
       this.postCode = postCode;
       this.town = town;
       this.countyId = countyId;
       this.countryId = countryId;
       this.typeOfBusinessId = typeOfBusinessId;
       this.fullDesc = fullDesc;
       this.phoneNumber = phoneNumber;
       this.fax = fax;
       this.email = email;
       this.webAddr = webAddr;
       this.charityNumber = charityNumber;
       this.companyNumber = companyNumber;
       this.organisationId = organisationId;
       this.isActive = isActive;
       this.departmentses = departmentses;
    }
   
    public int getDirectorateId() {
        return this.directorateId;
    }
    
    public void setDirectorateId(int directorateId) {
        this.directorateId = directorateId;
    }
    public Contacts getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Contacts contacts) {
        this.contacts = contacts;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortDesc() {
        return this.shortDesc;
    }
    
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
    }
    public Boolean getCopyAddrOrg() {
        return this.copyAddrOrg;
    }
    
    public void setCopyAddrOrg(Boolean copyAddrOrg) {
        this.copyAddrOrg = copyAddrOrg;
    }
    public String getAddr1() {
        return this.addr1;
    }
    
    public void setAddr1(String addr1) {
        this.addr1 = addr1;
    }
    public String getAddr2() {
        return this.addr2;
    }
    
    public void setAddr2(String addr2) {
        this.addr2 = addr2;
    }
    public String getAddr3() {
        return this.addr3;
    }
    
    public void setAddr3(String addr3) {
        this.addr3 = addr3;
    }
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getCountyId() {
        return this.countyId;
    }
    
    public void setCountyId(String countyId) {
        this.countyId = countyId;
    }
    public String getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(String countryId) {
        this.countryId = countryId;
    }
    public Integer getTypeOfBusinessId() {
        return this.typeOfBusinessId;
    }
    
    public void setTypeOfBusinessId(Integer typeOfBusinessId) {
        this.typeOfBusinessId = typeOfBusinessId;
    }
    public String getFullDesc() {
        return this.fullDesc;
    }
    
    public void setFullDesc(String fullDesc) {
        this.fullDesc = fullDesc;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebAddr() {
        return this.webAddr;
    }
    
    public void setWebAddr(String webAddr) {
        this.webAddr = webAddr;
    }
    public String getCharityNumber() {
        return this.charityNumber;
    }
    
    public void setCharityNumber(String charityNumber) {
        this.charityNumber = charityNumber;
    }
    public String getCompanyNumber() {
        return this.companyNumber;
    }
    
    public void setCompanyNumber(String companyNumber) {
        this.companyNumber = companyNumber;
    }
    public Integer getOrganisationId() {
        return this.organisationId;
    }
    
    public void setOrganisationId(Integer organisationId) {
        this.organisationId = organisationId;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set<Departments> getDepartmentses() {
        return this.departmentses;
    }
    
    public void setDepartmentses(Set<Departments> departmentses) {
        this.departmentses = departmentses;
    }




}


