package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Programmes generated by hbm2java
 */
public class Programmes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int programmeId;
	private Contacts contacts;
	private String name;
	private String description;
	private Boolean isActive;
	private Set<OrganisationProgramme> organisationProgrammes = new HashSet<OrganisationProgramme>(
			0);

	public Programmes() {
	}

	public Programmes(int programmeId) {
		this.programmeId = programmeId;
	}

	public Programmes(int programmeId, Contacts contacts, String name,
			String description, Boolean isActive,
			Set<OrganisationProgramme> organisationProgrammes) {
		this.programmeId = programmeId;
		this.contacts = contacts;
		this.name = name;
		this.description = description;
		this.isActive = isActive;
		this.organisationProgrammes = organisationProgrammes;
	}

	public int getProgrammeId() {
		return this.programmeId;
	}

	public void setProgrammeId(int programmeId) {
		this.programmeId = programmeId;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Set<OrganisationProgramme> getOrganisationProgrammes() {
		return this.organisationProgrammes;
	}

	public void setOrganisationProgrammes(
			Set<OrganisationProgramme> organisationProgrammes) {
		this.organisationProgrammes = organisationProgrammes;
	}

}
