package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Towns generated by hbm2java
 */
public class Towns implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int townId;
	private Counties counties;
	private String name;
	private Set<Addresses> addresseses = new HashSet<Addresses>(0);

	public Towns() {
	}

	public Towns(int townId) {
		this.townId = townId;
	}

	public Towns(int townId, Counties counties, String name,
			Set<Addresses> addresseses) {
		this.townId = townId;
		this.counties = counties;
		this.name = name;
		this.addresseses = addresseses;
	}

	public int getTownId() {
		return this.townId;
	}

	public void setTownId(int townId) {
		this.townId = townId;
	}

	public Counties getCounties() {
		return this.counties;
	}

	public void setCounties(Counties counties) {
		this.counties = counties;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Addresses> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresses> addresseses) {
		this.addresseses = addresseses;
	}

}
