package fsoft.xdev.mock.models;

// Generated Dec 6, 2011 8:45:37 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Volunteers generated by hbm2java
 */
public class Volunteers implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int volunteerId;
	private Contacts contacts;
	private String volunteerPurpose;
	private String details;
	private Date startDate;
	private Date endDate;
	private Integer premiseId;
	private Integer volunteerNo;
	private Boolean isActive;

	public Volunteers() {
	}

	public Volunteers(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public Volunteers(int volunteerId, Contacts contacts,
			String volunteerPurpose, String details, Date startDate,
			Date endDate, Integer premiseId, Integer volunteerNo,
			Boolean isActive) {
		this.volunteerId = volunteerId;
		this.contacts = contacts;
		this.volunteerPurpose = volunteerPurpose;
		this.details = details;
		this.startDate = startDate;
		this.endDate = endDate;
		this.premiseId = premiseId;
		this.volunteerNo = volunteerNo;
		this.isActive = isActive;
	}

	public int getVolunteerId() {
		return this.volunteerId;
	}

	public void setVolunteerId(int volunteerId) {
		this.volunteerId = volunteerId;
	}

	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	public String getVolunteerPurpose() {
		return this.volunteerPurpose;
	}

	public void setVolunteerPurpose(String volunteerPurpose) {
		this.volunteerPurpose = volunteerPurpose;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getPremiseId() {
		return this.premiseId;
	}

	public void setPremiseId(Integer premiseId) {
		this.premiseId = premiseId;
	}

	public Integer getVolunteerNo() {
		return this.volunteerNo;
	}

	public void setVolunteerNo(Integer volunteerNo) {
		this.volunteerNo = volunteerNo;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
